#!/usr/bin/env python3
"""Pasco County city pages for geo_content — excludes New Port Richey (defined in geo_content.py)."""
from geo_content import C, G, PASCO, PASCO_L

PASCO_CITIES: list[dict] = []

PASCO_CITIES.append(C(
    "port-richey-screen-repair", "Port Richey", PASCO, PASCO_L,
    "Pool Cage Rescreen Port Richey FL | Super Gutters | Screen Team",
    "Pool cage rescreen, lanai repair &amp; super gutters in Port Richey, FL. Minutes from our NPR base. Chris Westcott. (727) 386-6562.",
    "pool cage rescreen Port Richey FL, screen repair Port Richey, super gutters Port Richey, lanai repair west Pasco",
    "Pool Cage Rescreen &amp; Super Gutters in Port Richey, FL",
    "Waterfront and inland Port Richey cages — full rescreens, new-enclosure partner inquiries, and super gutters with fast scheduling from next-door New Port Richey.",
    "Port Richey — west Pasco waterfront wear, neighbor-city speed",
    [
        "Port Richey hugs the Gulf side of US-19 where canal fingers reach behind modest ranch homes and 1980s pool cages that have weathered four decades of salt mist without anyone swapping the bottom row. Chris Westcott treats <strong>pool cage rescreen Port Richey FL</strong> calls as extension-of-home-base work — Screen Team is headquartered in New Port Richey, so a Port Richey address often lands on the same-week calendar that cross-bay Pinellas jobs wait longer to reach. Canal lots get inspected for white corrosion on kick plates and hinge hardware before mesh is quoted; inland pockets east of the highway show rooftop oxidation from relentless afternoon sun instead.",
        "Homeowners here rarely need a lecture about Florida screening — they need someone who will say whether a storm tear is a two-panel patch or the signal that every wall has turned chalky. Chris walks the enclosure, checks door sag on lanais that face open water, and explains partial versus full scope without upselling a cage that still has years left. When the aluminum is sound but mesh is uniformly brittle, a <a href=\"rescreens.html\">full pool cage rescreen</a> restores tension across roof horizontals and walls in a single visit on typical footprints.",
        "Priority demand in Port Richey mirrors the rest of west Pasco: rescreens when oxidation wins, partner-path conversations for brand-new enclosures on vacant pads, and super gutters when oak litter and squall water keep soaking the header. Porch refreshes, window screens, and single storm panels still book on the same trip — you are not forced into a whole-cage quote when a door or two bays need attention. Call or text <a href=\"tel:7273866562\">(727) 386-6562</a> with wide shots plus close-ups of the worst bay and mention whether your lot is canal-side or inland east of US-19.",
    ],
    "Port Richey areas we know",
    [
        ("<strong>Canal / waterfront streets</strong>", "salt-tinged lower horizontals, hinge corrosion on west-facing doors"),
        ("<strong>US-19 east-side pockets</strong>", "mid-size cages with spline failure before roof panels fail"),
        ("<strong>Old Post Road corridor</strong>", "ranch lanais, porch screen batches, quick door repairs"),
        ("<strong>Regency Park / NPR border</strong>", "paired scheduling with New Port Richey on the same loop"),
        ("<strong>Sims Park adjacency</strong>", "compact downtown lanais and older aluminum stock"),
    ],
    "<strong>West Pasco loop:</strong> Port Richey batches with <a href=\"new-port-richey-screen-repair.html\">New Port Richey</a> and <a href=\"holiday-screen-repair.html\">Holiday</a> — mention a second Pasco address when you call.",
    "Rescreens, new enclosures, and super gutters in Port Richey",
    [
        "A full <a href=\"rescreens.html\">pool cage rescreen</a> is the honest fix when every wall snaps under finger pressure and roof horizontals sag like wet laundry. Chris strips failed mesh, verifies posts are still plumb, seats fresh spline with proper tension, and finishes the door leaf so the latch catches clean — usually in one day on standard single-story cages along the US-19 corridor. If only the bottom row failed from salt while upper bays remain tight, he quotes that row instead of selling a whole-cage job you do not need yet.",
        "Shopping for a new pool cage on a cleared lot or replacing a storm-collapsed structure? Chris opens a <a href=\"pool-enclosures.html\">new enclosure inquiry</a> and routes engineering, permits, and structural work through licensed partners while staying your local point of contact. You are not handed off to a call center with no Tampa Bay context — the same owner who rescreens your neighbor's lanai coordinates the conversation from first photo to permit questions.",
        "Super gutters along the cage roof solve the Port Richey pattern of shallow troughs clogging with oak leaves until water sheets onto fascia and rots spline along the top plate. Pair <a href=\"gutters-and-screens.html\">gutters and screens</a> or <a href=\"gutter-work.html\">gutter work</a> with a rescreen so you are not paying for two ladder setups in the same season. Window screens, lanai door patches, and <a href=\"storm-screen-repair.html\">storm repairs</a> after squalls still qualify when they meet the job minimum — mention small work when you book the big job.",
    ],
    "Coastal humidity vs inland Port Richey lots",
    [
        "Canal-facing cages show white hardware corrosion and chalky bottom rows years before inland roofs fail. Chris inspects salt damage on lower kick plates and door hinges first when open water sits behind the lot; east-of-US-19 homes get roof horizontals checked first because UV and wind-driven rain peel those panels before salt reaches the walls. After tropical systems, photograph every torn bay before calling — partial storm work often restores the cage when posts remain square.",
        "Steady Gulf breeze fatigues west-facing door spline even when mesh looks fine. If the latch will not catch, the door panel — not the roof — is often the first repair. Pet traffic on family cages near Regency Park gets <a href=\"pet-resistant-screen-mesh.html\">pet-resistant mesh</a> on the abuse door when standard fiberglass keeps failing after repeat patches.",
    ],
    [
        ("new-port-richey-screen-repair.html", "New Port Richey"),
        ("holiday-screen-repair.html", "Holiday"),
        ("hudson-screen-repair.html", "Hudson"),
        ("tarpon-springs-screen-repair.html", "Tarpon Springs"),
        ("pasco-county-screen-repair.html", "Pasco hub"),
        ("rescreens.html", "Rescreens"),
        ("gutter-work.html", "Gutter work"),
        ("pool-enclosures.html", "New enclosures"),
        ("pool-cage-repair.html", "Cage repair"),
    ],
    [
        ("Do you serve Port Richey separately from New Port Richey?", "Yes. Port Richey is a core west Pasco stop — often same-week from our NPR home base."),
        ("Can salt-damaged lower panels be replaced alone?", "Often yes when upper mesh is still tight and aluminum feet are sound — Chris quotes from photos or on site."),
        ("Do you handle new pool cage builds in Port Richey?", "New enclosure inquiries use our licensed partner path when permits and engineering are required. Call Chris to start."),
        ("Are super gutters available on older Port Richey cages?", "Yes, when the header and frame can support oversized enclosure gutters — quoted on site or from detailed photos."),
        ("How fast can you schedule Port Richey cage work?", "Port Richey frequently books faster than Pinellas or Hillsborough routes. Call (727) 386-6562 with photos."),
    ],
    [
        ("<strong>Note canal access</strong>", "Dock-side or seawall ladder setup needs a heads-up before arrival."),
        ("<strong>Photo bottom row + roof</strong>", "Salt wear and storm damage look different — both shots help Chris scope accurately."),
        ("<strong>Ask about gutters</strong>", "If water sheets off the cage roof after light rain, mention super gutters early."),
    ],
    "Port Richey pool cage rescreen — west Pasco owner-direct service.",
    [(G["pano2"], "Port Richey pool cage coastal rescreen"), (G["cage4"], "Lanai repair Port Richey Florida"), (G["side"], "Screen enclosure panels Port Richey"), (G["mesh"], "Mesh replacement Port Richey Pasco")],
    [(G["pano2"], "Coastal cage work — Port Richey"), (G["cage1"], "Pool enclosure — west Pasco")],
))

PASCO_CITIES.append(C(
    "trinity-screen-repair", "Trinity", PASCO, PASCO_L,
    "Screen Repair Trinity FL | Mitchell Ranch Cages | Screen Team",
    "Pool cage rescreen &amp; lanai repair in Trinity, FL — Mitchell Ranch, Trinity Oaks &amp; inland Pasco HOAs. Chris Westcott. (727) 386-6562.",
    "screen repair Trinity FL, pool cage rescreen Trinity, lanai screen repair Mitchell Ranch, screen enclosure inland Pasco",
    "Screen Repair &amp; Pool Cage Rescreens in Trinity, FL",
    "Inland Pasco family neighborhoods — newer cages hitting first oxidation, HOA-scale enclosures, and honest rescreen quotes from Chris Westcott.",
    "Trinity — inland Pasco, first oxidation on newer stock",
    [
        "Trinity sits inland from the Gulf surge zones where Pasco's master-planned wave planted Mitchell Ranch, Trinity Oaks, and long streets of two-story homes with cages that still look new from the curb — until you press a roof panel and hear the fiberglass crackle. <strong>Screen repair Trinity FL</strong> searches spike when those first-decade enclosures cross from builder-grade tightness into uniform chalkiness, especially on south-facing walls that bake while kids and dogs hammer the lanai door all summer. Chris Westcott routes Trinity on east-Pasco days paired with Land O Lakes or Wesley Chapel, not as an afterthought from a dispatcher who has never seen a Mitchell Ranch cul-de-sac.",
        "HOA communities here mean consistent cage footprints but different maintenance timelines — snowbirds in one phase, year-round families in the next, and rental turnovers that discover torn spline the week before listing photos. Chris inspects door alignment on great-room lanais, checks whether oxidation is cage-wide or isolated to the abuse panel, and quotes partial work when the frame still has years left. Full <a href=\"rescreens.html\">pool cage rescreens</a> land when every bay fails the finger test, not because a sales script says so.",
        "Trinity homeowners also ask about upgrades during that first rescreen window — pet mesh on the door the Labrador uses, clearer visibility fiberglass, or <a href=\"no-see-um-screen.html\">no-see-um screening</a> when gnats ruin evening pool time. Chris prices line items so you choose before mesh goes up, and he will tell you when builder-grade screen simply will not last another five years without a full refresh. Text photos to <a href=\"tel:7273866562\">(727) 386-6562</a> with your subdivision name, gate code if applicable, and whether the cage is single or two-story.",
    ],
    "Trinity neighborhoods &amp; enclosure types",
    [
        ("<strong>Mitchell Ranch</strong>", "family HOAs, two-story cages, first full rescreens at year twelve"),
        ("<strong>Trinity Oaks / Champions Club</strong>", "golf-community lanais, door spline before roof failure"),
        ("<strong>Little Rd / SR-54 interior</strong>", "2000s–2010s stock entering oxidation together"),
        ("<strong>Foxwood / Trinity Lakes</strong>", "pet-damaged door panels, standard mesh fatigue"),
        ("<strong>Pasco-Pinellas border streets</strong>", "paired scheduling with Palm Harbor or East Lake runs"),
    ],
    "<strong>Inland Pasco routing:</strong> Trinity pairs with <a href=\"odessa-screen-repair.html\">Odessa</a> and <a href=\"land-o-lakes-screen-repair.html\">Land O Lakes</a> on east-county days — name your HOA when you call.",
    "Priority work in Trinity: rescreens, new cages, super gutters",
    [
        "The dominant Trinity call is a first full <a href=\"rescreens.html\">pool cage rescreen</a> on a cage that still looks presentable from the street. Chris removes uniformly oxidized mesh, verifies posts and headers on newer aluminum that has not yet corroded, and tension-tests every bay so the roof stops holding puddles after afternoon storms. Partial quotes stay on the table when only the door and one wall show abuse — common in Mitchell Ranch homes where teenagers use the same hinge-side panel all year.",
        "Empty lots and tear-down rebuilds in Trinity's continuing build-out sometimes need a brand-new enclosure rather than a rescreen on tired aluminum. Chris starts those on <a href=\"pool-enclosures.html\">pool enclosures</a> and connects engineering and permit paths through licensed partners while remaining your local contact for access notes, HOA height rules, and mesh preferences. You keep one phone number from first inquiry through install coordination — no handoff to a distant office that has never driven Mitchell Ranch.",
        "Super gutters matter on Trinity cages where oak canopy from maturing street trees dumps leaves into shallow builder troughs. Overflow stains fascia and softens spline along the header — ask about <a href=\"gutters-and-screens.html\">gutters and screens</a> when rescreening. <a href=\"gutter-work.html\">Gutter work</a> on the house tie-in can ride the same visit. Window screen batches, porch panels, and single storm repairs still book alongside cage work for homeowners who want one ladder trip.",
    ],
    "Inland Trinity weather on pool cages",
    [
        "Without Gulf salt, Trinity cages fail from UV and afternoon thunderstorm wind more than corrosion. Chris checks roof horizontals first on inland lots where squalls peel slack panels before lower walls show wear. Uniform gray mesh across every bay usually means rescreen season has arrived — patching one tear on oxidized neighbors buys months, not years.",
        "Two-story cages in Trinity Oaks and Mitchell Ranch add ladder time and wind exposure on upper panels. Height and side-yard access get priced upfront so you are not surprised on arrival. After named storms, <a href=\"storm-screen-repair.html\">storm screen repair</a> restores torn sections when posts remain plumb — Chris will say when a full refresh is the better long-term fix.",
    ],
    [
        ("odessa-screen-repair.html", "Odessa"),
        ("land-o-lakes-screen-repair.html", "Land O Lakes"),
        ("wesley-chapel-screen-repair.html", "Wesley Chapel"),
        ("new-port-richey-screen-repair.html", "New Port Richey"),
        ("pasco-county-screen-repair.html", "Pasco hub"),
        ("rescreens.html", "Rescreens"),
        ("pool-enclosures.html", "New enclosures"),
        ("gutters-and-screens.html", "Super gutters"),
        ("palm-harbor-screen-repair.html", "Palm Harbor"),
    ],
    [
        ("Is Trinity in your regular service area?", "Yes. Inland Pasco including Trinity is within our typical coverage — often scheduled with east-county routes."),
        ("My Mitchell Ranch cage is only ten years old — why is mesh failing?", "Florida UV and daily door use age builder-grade mesh faster than northern climates. Chris inspects before quoting full vs partial."),
        ("Do you work in gated Trinity HOAs?", "Yes. Provide gate instructions and community name when booking — Chris works in HOA neighborhoods daily."),
        ("Can you upgrade to pet mesh during a Trinity rescreen?", "Yes. Door-only or lower-wall pet upgrades are common — priced as clear line items."),
        ("Do you install super gutters on newer Trinity cages?", "Yes when the header can support oversized enclosure gutters — often bundled with a rescreen visit."),
    ],
    [
        ("<strong>Name the subdivision</strong>", "Mitchell Ranch, Trinity Oaks, etc. — speeds gate and routing planning."),
        ("<strong>Note two-story height</strong>", "Upper roof panels need ladder planning — mention stories in your first text."),
        ("<strong>Photo door + worst wall</strong>", "Abuse panels and oxidation patterns scope faster than wide shots alone."),
    ],
    "Trinity screen repair — inland Pasco cages, owner on every ladder.",
    [(G["cage3"], "Pool cage rescreen Trinity Mitchell Ranch"), (G["tall"], "Two-story enclosure Trinity Pasco"), (G["door"], "Lanai door repair Trinity FL"), (G["pano1"], "Screen enclosure inland Pasco County")],
    [(G["cage2"], "Family pool cage — Trinity area"), (G["done"], "Completed rescreen — inland Pasco")],
))

PASCO_CITIES.append(C(
    "odessa-screen-repair", "Odessa", PASCO, PASCO_L,
    "Pool Cage Rescreen Odessa FL | Tall Cages & Lakes | Screen Team",
    "Pool cage rescreen &amp; tall enclosure repair in Odessa, FL — Keystone-Odessa lakes, large lots &amp; rural-suburban cages. (727) 386-6562.",
    "pool cage rescreen Odessa FL, screen repair Odessa, tall pool cage Odessa, screen enclosure Keystone Odessa lakes",
    "Pool Cage Rescreen &amp; Tall Enclosures in Odessa, FL",
    "Keystone-Odessa lake lots and rural-suburban acreage — tall cages, long driveways, and rescreens priced for real access and height.",
    "Odessa — lake lots, large lots, taller cages",
    [
        "Odessa stretches across Keystone-Odessa lake country where half-acre lots hide tall pool cages, detached lanais, and screened porches that never fit the cookie-cutter footprint templates west Pasco subdivisions use. <strong>Pool cage rescreen Odessa FL</strong> jobs demand honest talk about ladder setup, side-yard clearance, and whether your cage clears the second story — Chris Westcott prices height and access in the first conversation because a per-panel quote that ignores a twenty-foot roof line wastes everyone's afternoon. Screen Team routes Odessa on inland Pasco days, often paired with Trinity or Land O Lakes addresses along the same SR-54 corridor.",
        "Housing stock here mixes 1990s lake houses with newer builds on former pasture where every backyard seems to include a diving board and a cage tall enough to need scaffold planning. Oxidation still wins on the same timeline as flatter neighborhoods — roof horizontals turn gray, spline pops on doors facing the dock, and afternoon storms peel slack upper panels before lower walls show wear. Chris inspects aluminum feet near lake moisture, checks for corrosion where sprinklers hit kick plates, and tells you whether a partial bay replacement or a <a href=\"rescreens.html\">full pool cage rescreen</a> matches the cage's real condition.",
        "Rural-suburban Odessa also means longer drives from our New Port Richey base — Chris schedules efficiently by batching lake-road properties and confirms travel when you book so you are not waiting on a vague arrival window. That honesty about east-county routing beats promising same-day service that never materializes. Text wide exterior shots, a roof close-up, and any gate or easement notes to <a href=\"tel:7273866562\">(727) 386-6562</a>. Porch screens, garage batches, and dock-side lanais ride along when you are already paying for the trip.",
    ],
    "Odessa areas &amp; enclosure profiles",
    [
        ("<strong>Keystone-Odessa lake roads</strong>", "tall cages, dock-side access, humidity at the waterline"),
        ("<strong>Pleasant Lake / Lake Frances</strong>", "large footprints, multi-bay roof sections"),
        ("<strong>Gunn Hwy / SR-54 interior</strong>", "rural-suburban transitions, mixed cage ages"),
        ("<strong>Starkey Ranch border</strong>", "newer stock meeting first oxidation wave"),
        ("<strong>Seven Springs adjacency</strong>", "wooded lots, leaf load on cage gutters"),
    ],
    "<strong>Lake-country routing:</strong> Odessa batches with <a href=\"trinity-screen-repair.html\">Trinity</a> and <a href=\"land-o-lakes-screen-repair.html\">Land O Lakes</a> — mention long driveways and gate codes when you call.",
    "Rescreens, new enclosures, and super gutters in Odessa",
    [
        "Tall and wide cages dominate Odessa rescreen quotes. Chris strips oxidized mesh bay by bay, confirms the frame is square after years of wind off open water, and installs new screen with tension that stops roof puddles — work that may span two days on the largest lake-house footprints. A full <a href=\"rescreens.html\">pool cage rescreen</a> beats patching when every panel snaps in your fingers; partial quotes stay available when only storm rows or a single abuse wall failed.",
        "Cleared lots and major rebuilds on Odessa acreage sometimes need a new enclosure rather than mesh on tired aluminum. Chris opens <a href=\"pool-enclosures.html\">new enclosure inquiries</a> and coordinates permits and engineering through licensed partners while staying your local contact for lot access, setback questions, and mesh choices. You are not cold-transferred to a stranger who has never driven Gunn Highway — the owner who quotes your rescreen stays on the thread until partners take over structural work.",
        "Wooded Odessa lots clog shallow cage gutters with oak and pine litter until water overflows onto spline along the header. Super gutters and <a href=\"gutters-and-screens.html\">gutters and screens</a> bundles make sense during a rescreen when Chris is already on ladders — see also <a href=\"gutter-work.html\">gutter work</a> for house tie-ins. Small jobs — window screens, single panels, <a href=\"storm-screen-repair.html\">storm patches</a> — still book when they meet the minimum and you are already on the schedule.",
    ],
    "Lake humidity and inland wind on Odessa cages",
    [
        "Lake lots add humidity at the waterline without the salt corrosion Gulf canal homes see — Chris watches for soft aluminum feet and sprinkler staining on lower kick plates. Inland wind across open acreage fatigues roof horizontals and upper door spline on west-facing bays. After summer squalls, photograph torn sections before they flap into larger tears.",
        "Tall cages catch harder UV on upper panels that fail years before lower walls on shaded lots. Height access is priced upfront, not discovered mid-job. When upper bays are slack but lower mesh is sound, Chris can scope upper-row replacement — and will warn if color mismatch will show from the dock.",
    ],
    [
        ("trinity-screen-repair.html", "Trinity"),
        ("land-o-lakes-screen-repair.html", "Land O Lakes"),
        ("zephyrhills-screen-repair.html", "Zephyrhills"),
        ("new-port-richey-screen-repair.html", "New Port Richey"),
        ("pasco-county-screen-repair.html", "Pasco hub"),
        ("rescreens.html", "Rescreens"),
        ("pool-enclosures.html", "New enclosures"),
        ("gutters-and-screens.html", "Super gutters"),
        ("lanai-screen-replacement.html", "Lanai replacement"),
    ],
    [
        ("Do you serve Keystone and Odessa lake roads?", "Yes. Lake-country Odessa is regular inland Pasco territory — travel confirmed when you book."),
        ("How do you quote tall Odessa pool cages?", "Height, access, and bay count are priced upfront from photos showing the full cage elevation."),
        ("Is there a travel charge for rural Odessa addresses?", "Chris batches east Pasco routes — you hear realistic scheduling and travel notes when you call, not surprise fees on arrival."),
        ("Can you rescreen a cage with dock-side ladder access only?", "Often yes with advance notice. Mention dock, seawall, or easement constraints in your first message."),
        ("Do you handle new pool cages on Odessa acreage?", "New enclosure inquiries use our partner path for permits and engineering — start on pool enclosures and call Chris."),
    ],
    [
        ("<strong>Send height photos</strong>", "Show the cage relative to the house roof — tall work needs planning."),
        ("<strong>Note driveway / gate access</strong>", "Long rural drives and coded gates affect arrival and equipment."),
        ("<strong>Mention lake vs interior lot</strong>", "Waterfront humidity and wooded leaf load change the inspection order."),
    ],
    "Odessa pool cage rescreen — tall enclosures, honest lake-country quotes.",
    [(G["tall"], "Tall pool cage rescreen Odessa FL"), (G["pano3"], "Lake lot enclosure Keystone Odessa"), (G["cage1"], "Large footprint cage Odessa Pasco"), (G["work"], "Screen enclosure work rural Pasco")],
    [(G["pano3"], "Odessa lake-country cage"), (G["rescreen"], "Full rescreen — east Pasco")],
))

PASCO_CITIES.append(C(
    "zephyrhills-screen-repair", "Zephyrhills", PASCO, PASCO_L,
    "Screen Repair Zephyrhills FL | East Pasco Cages | Screen Team",
    "Pool cage rescreen &amp; lanai repair in Zephyrhills, FL — downtown stock, east Pasco subdivisions &amp; storm wear. Chris Westcott. (727) 386-6562.",
    "screen repair Zephyrhills FL, pool cage rescreen Zephyrhills, lanai screen repair east Pasco, screen enclosure Zephyrhills",
    "Screen Repair &amp; Pool Cage Rescreens in Zephyrhills, FL",
    "East Pasco inland — historic downtown cages, newer subdivisions off SR-54, and afternoon storm wear on roof panels.",
    "Zephyrhills — east Pasco inland, storms and mixed-era stock",
    [
        "Zephyrhills wears two faces: a walkable downtown core with older ranch homes and screened porches that predate the SR-54 boom, and ring suburbs where 2000s subdivisions brought standard pool cages now entering their first oxidation cycle. <strong>Screen repair Zephyrhills FL</strong> calls reflect that split — downtown owners need porch panel batches and sagging lanai doors, while east-side neighborhoods ask about full <a href=\"rescreens.html\">pool cage rescreens</a> when builder mesh turned chalky uniformly. Chris Westcott drives east Pasco on dedicated days; Zephyrhills sits farther from the NPR home base than west Pasco, so travel gets confirmed honestly when you book rather than promised as same-day magic.",
        "Inland heat and afternoon thunderstorm lines hit Zephyrhills cages harder than Gulf breeze corrosion. Roof horizontals peel first when mesh loses tension; Chris checks slack panels that hold standing water after rain because weight accelerates the next tear across the whole roof line. Downtown lots near 5th Avenue often have compact lanais where door spline fails before walls look bad — a hardware-and-panel fix, not an automatic full-cage quote, and Chris will say which you actually need after walking the enclosure.",
        "Chris inspects every enclosure on its merits: partial storm rows after a squall, abuse doors on family pools in Silver Oaks, or a complete refresh when oxidation is cage-wide. He does not sell a whole structure because one panel tore in last week's wind — and he will not patch three bays when every wall is chalky. Text subdivision or cross-street context plus photos to <a href=\"tel:7273866562\">(727) 386-6562</a>. Window screens, porch refreshes, and garage batches can ride along when you are already paying for the east-county trip.",
    ],
    "Zephyrhills areas we work",
    [
        ("<strong>Downtown / historic core</strong>", "compact lanais, porch screens, older aluminum"),
        ("<strong>Silver Oaks / Oakcrest</strong>", "family pools, first-decade oxidation"),
        ("<strong>SR-54 east corridor</strong>", "commuter subdivisions, standard cage footprints"),
        ("<strong>Zephyr Lake / Hercules Rd</strong>", "wooded lots, leaf load on gutters"),
        ("<strong>Dade City adjacency</strong>", "paired scheduling on east Pasco days"),
    ],
    "<strong>East Pasco note:</strong> Zephyrhills routes with <a href=\"dade-city-screen-repair.html\">Dade City</a> and <a href=\"wesley-chapel-screen-repair.html\">Wesley Chapel</a> — longer drive from NPR, confirmed at booking.",
    "Priority work in Zephyrhills: rescreens, new cages, super gutters",
    [
        "Full <a href=\"rescreens.html\">pool cage rescreens</a> make sense in Zephyrhills when every bay fails the chalk test — common on fifteen-year-old mesh in Silver Oaks and similar subdivisions. Chris removes brittle screen, verifies posts and headers, and rolls new mesh with spline tension that survives the next storm season. Downtown owners with smaller footprints often finish in a single day; larger east-side cages may need a second day when bay count and height add ladder time.",
        "Vacant pads and major rebuilds east of downtown sometimes need a new enclosure instead of rescreening tired frame sections. Start on <a href=\"pool-enclosures.html\">pool enclosures</a> and Chris coordinates partner-path permits and engineering while staying your local contact. You keep one owner-direct phone line from first photo through HOA or county questions — no franchise dispatcher reading a script about coverage areas Chris already drives weekly on east Pasco days.",
        "Oak and pine litter clogs shallow cage gutters on wooded Zephyrhills lots until overflow soaks the header spline. Bundle <a href=\"gutters-and-screens.html\">gutters and screens</a> or <a href=\"gutter-work.html\">gutter work</a> with a rescreen when Chris is already on ladders. Small jobs — single storm panels, window screens, porch patches — still qualify alongside the main cage work when they meet the job minimum.",
    ],
    "Inland storms and heat on Zephyrhills enclosures",
    [
        "East Pasco afternoon storms track inland with wind that peels slack roof panels before lower walls show wear. Chris replaces torn horizontals after squalls when posts remain plumb — see <a href=\"storm-screen-repair.html\">storm screen repair</a>. When oxidation is uniform, patching one bay on chalky neighbors buys months, not years, and he will say so.",
        "Without coastal salt, failure modes here are UV embrittlement and gutter overflow more than hinge corrosion. Shaded downtown porches age slower than open east-side pools baked all afternoon. Pet doors on family cages get <a href=\"pet-resistant-screen-mesh.html\">pet-resistant mesh</a> when repeat patches stop holding.",
    ],
    [
        ("dade-city-screen-repair.html", "Dade City"),
        ("wesley-chapel-screen-repair.html", "Wesley Chapel"),
        ("land-o-lakes-screen-repair.html", "Land O Lakes"),
        ("odessa-screen-repair.html", "Odessa"),
        ("pasco-county-screen-repair.html", "Pasco hub"),
        ("rescreens.html", "Rescreens"),
        ("pool-enclosures.html", "New enclosures"),
        ("gutters-and-screens.html", "Super gutters"),
        ("storm-screen-repair.html", "Storm repair"),
    ],
    [
        ("Is Zephyrhills within your service area?", "Yes. East Pasco including Zephyrhills is covered — travel time from NPR is confirmed when you schedule."),
        ("Why do my roof panels fail before walls in Zephyrhills?", "Inland sun and storm wind stress horizontals first when mesh loses tension. Chris inspects roof rows on every quote."),
        ("Do you repair downtown Zephyrhills porch screens?", "Yes. Compact lanais and porch panels are common downtown — often quicker than full cage jobs."),
        ("Can you help with a new pool cage east of SR-54?", "New enclosure inquiries use our licensed partner path — call Chris to start on pool enclosures."),
        ("Do you install super gutters on Zephyrhills cages?", "Yes when the frame supports oversized troughs — often quoted with a full rescreen visit."),
    ],
    [
        ("<strong>Say downtown vs subdivision</strong>", "Historic core and SR-54 suburbs scope differently — location helps."),
        ("<strong>Photo roof from inside</strong>", "Looking up after rain shows slack panels that need attention."),
        ("<strong>Confirm east Pasco day</strong>", "Zephyrhills is batched with nearby east-county cities for efficient routing."),
    ],
    "Zephyrhills screen repair — east Pasco cages, storms and honest scope.",
    [(G["porch"], "Porch screen repair Zephyrhills downtown"), (G["cage2"], "Pool cage rescreen east Pasco"), (G["lanai"], "Lanai door repair Zephyrhills FL"), (G["pano1"], "Screen enclosure Zephyrhills area")],
    [(G["cage3"], "Completed cage work — Zephyrhills"), (G["mesh"], "Mesh replacement east Pasco County")],
))

PASCO_CITIES.append(C(
    "dade-city-screen-repair", "Dade City", PASCO, PASCO_L,
    "Screen Repair Dade City FL | Pasco County Seat | Screen Team",
    "Pool cage rescreen &amp; lanai repair in Dade City, FL — historic downtown, rural edges &amp; east Pasco. Chris Westcott. (727) 386-6562.",
    "screen repair Dade City FL, pool cage rescreen Dade City, lanai repair Pasco county seat, screen enclosure east Pasco rural",
    "Screen Repair &amp; Pool Cages in Dade City, FL",
    "Pasco's county seat — historic downtown porches, rural-acreage cages, and honest scheduling from our west Pasco home base.",
    "Dade City — county seat, historic core, rural edges",
    [
        "Dade City anchors east Pasco as the county seat — brick storefronts and oaks along Meridian Avenue sit minutes from pasture lots where screened pools stretch across acreage no west Pasco subdivision planner ever imagined. <strong>Screen repair Dade City FL</strong> searches come from both worlds: downtown homeowners fixing porch screens and sagging lanai doors on bungalows near the courthouse, and rural properties needing full <a href=\"rescreens.html\">pool cage rescreens</a> on tall enclosures half a mile off the pavement. Chris Westcott serves Dade City on dedicated east-county days; it is a longer drive from New Port Richey than Holiday or Port Richey, and he tells you that upfront so expectations stay realistic.",
        "Historic housing near downtown often has compact screened additions where spline failure and door misalignment cause more trouble than roof tears — Chris aligns latches and replaces hinge-side mesh before quoting a whole structure. Out toward Lacoochee and the rural edges, cages face open wind and leaf load from canopy trees that clog gutters until water rots spline along the header. Oxidation timelines match inland Florida: uniform chalkiness means rescreen season, not another temporary patch that fails by Thanksgiving when guests arrive.",
        "Batching matters for Dade City — Chris often pairs county-seat stops with Zephyrhills or Wesley Chapel runs so travel time stays efficient for everyone on the east Pasco loop. That is why he confirms scheduling windows honestly rather than overpromising same-week slots from west Pasco. Text photos with your road name, gate notes, and whether the job is downtown-scale or acreage-scale to <a href=\"tel:7273866562\">(727) 386-6562</a>. Porch panels, window screens, and storm patches ride along when you are already on the east Pasco schedule.",
    ],
    "Dade City areas &amp; enclosure types",
    [
        ("<strong>Historic downtown / Meridian Ave</strong>", "porch screens, compact lanais, older spline"),
        ("<strong>Lake Jovita / golf edges</strong>", "community cages, first oxidation on 2000s stock"),
        ("<strong>US-301 / SR-52 corridors</strong>", "mixed ranch and subdivision cages"),
        ("<strong>Rural Lacoochee direction</strong>", "large lots, tall cages, long drive access"),
        ("<strong>Zephyrhills border</strong>", "paired east Pasco scheduling"),
    ],
    "<strong>County seat routing:</strong> Dade City is east Pasco — longer from NPR than west coast cities. Chris batches with <a href=\"zephyrhills-screen-repair.html\">Zephyrhills</a> when possible.",
    "Rescreens, new enclosures, and super gutters in Dade City",
    [
        "When rural Dade City cages show uniform oxidation, a full <a href=\"rescreens.html\">pool cage rescreen</a> restores every bay with fresh tension — critical on tall enclosures where slack roof panels hold water weight after inland storms. Chris strips failed mesh, checks posts for plumb, and finishes doors so latches catch clean. Downtown jobs on smaller footprints often complete in a day; acreage cages with height and bay count may span two.",
        "New construction and rebuilds on east Pasco acreage sometimes need a partner-path enclosure instead of rescreening compromised aluminum. Chris starts those conversations on <a href=\"pool-enclosures.html\">pool enclosures</a> and coordinates permits and engineering through licensed partners while remaining your local contact. Rural setbacks, long drive access, and county-seat permit questions get discussed before anyone climbs a ladder — you are not surprised by scope on arrival day.",
        "Wooded rural lots clog cage gutters until overflow damages header spline — super gutters and <a href=\"gutters-and-screens.html\">gutters and screens</a> bundles make sense during rescreen visits. <a href=\"gutter-work.html\">Gutter work</a> on the house connection can share the trip. Small repairs — window screens, single panels, <a href=\"storm-screen-repair.html\">storm tears</a> — still book when they meet the minimum and you are already paying east-county travel.",
    ],
    "Inland east Pasco conditions on Dade City cages",
    [
        "Dade City skips Gulf salt but not afternoon thunderstorm wind or inland UV. Chris inspects roof horizontals first on open acreage where squalls peel slack mesh; downtown porches get door and spline checks first when walls still look tight. After named storms, partial repairs work when posts are sound — he will say when oxidation demands a full refresh instead.",
        "Canopy trees on rural roads dump leaves into shallow troughs until water sheets onto fascia. If the cage roof looks wet after light rain, mention gutters when you call. Pet abuse on family doors gets <a href=\"pet-resistant-screen-mesh.html\">pet-resistant mesh</a> when fiberglass keeps failing after patches.",
    ],
    [
        ("zephyrhills-screen-repair.html", "Zephyrhills"),
        ("wesley-chapel-screen-repair.html", "Wesley Chapel"),
        ("land-o-lakes-screen-repair.html", "Land O Lakes"),
        ("new-port-richey-screen-repair.html", "New Port Richey"),
        ("pasco-county-screen-repair.html", "Pasco hub"),
        ("rescreens.html", "Rescreens"),
        ("pool-enclosures.html", "New enclosures"),
        ("gutters-and-screens.html", "Super gutters"),
        ("lanai-screen-replacement.html", "Lanai replacement"),
    ],
    [
        ("How far is Dade City from your home base?", "Dade City is east Pasco — a longer drive from New Port Richey than west-coast cities. Chris confirms travel when you book."),
        ("Do you repair historic downtown porch screens?", "Yes. Compact porches and lanai doors near downtown are common Dade City jobs."),
        ("Can you rescreen tall cages on rural Dade City lots?", "Yes. Height and access are priced upfront from photos showing full cage elevation."),
        ("Do you handle new pool enclosures in east Pasco?", "New builds use our licensed partner path for permits — start on pool enclosures and call Chris."),
        ("Will you batch my job with Zephyrhills?", "Often on east Pasco days — mention if you have flexibility for efficient routing."),
    ],
    [
        ("<strong>Downtown vs rural address</strong>", "Scope and access differ — say which you are."),
        ("<strong>Long driveway / gate notes</strong>", "Acreage properties need access details before arrival."),
        ("<strong>Expect honest travel time</strong>", "East Pasco is served regularly — not always same-week like NPR."),
    ],
    "Dade City screen repair — county seat and rural east Pasco, owner-direct.",
    [(G["porch"], "Historic porch screen Dade City"), (G["cage4"], "Rural pool cage Dade City Pasco"), (G["tall"], "Tall enclosure east Pasco acreage"), (G["door"], "Lanai repair Dade City FL")],
    [(G["work"], "Screen work — Dade City area"), (G["done"], "Completed rescreen — east Pasco")],
))

PASCO_CITIES.append(C(
    "holiday-screen-repair", "Holiday", PASCO, PASCO_L,
    "Pool Cage Repair Holiday FL | Gulf Harbors | Screen Team",
    "Pool cage rescreen, lanai repair &amp; super gutters in Holiday, FL — Anclote, Gulf Harbors &amp; west Pasco coast. (727) 386-6562.",
    "pool cage repair Holiday FL, screen repair Holiday Florida, lanai rescreen Gulf Harbors, super gutters Holiday Pasco",
    "Pool Cage Repair, Rescreens &amp; Super Gutters in Holiday, FL",
    "Anclote River and Gulf Harbors coastal cages — among the fastest west Pasco scheduling from our New Port Richey home base.",
    "Holiday — Anclote waterfront, Gulf Harbors canals, home-base proximity",
    [
        "Holiday clusters along the Anclote River and Gulf Harbors canal system where screened pools catch Gulf humidity, open-water breeze, and afternoon squalls that peel roof horizontals before inland Pasco neighborhoods know a storm passed. <strong>Pool cage repair Holiday FL</strong> is core territory for Screen Team — New Port Richey home base sits minutes away, so Chris Westcott often slots Holiday the same week that Pinellas or Hillsborough routes wait for the next open day. Canal lots get lower-row inspections for salt mist and hinge corrosion; interior Holiday streets off US-19 deal more with UV oxidation on roofs and doors that lost spline from daily use.",
        "Gulf Harbors homeowners know the pattern: mesh looks acceptable from the driveway until you stand inside the cage and see chalky lower panels, water staining on kick plates, and a lanai door that drags because the hinge side gave up years ago. Chris fixes doors first when hardware is the real problem, quotes partial walls when salt ate only the bottom row, and recommends a full <a href=\"rescreens.html\">pool cage rescreen</a> when every bay fails the finger test. He is not selling a whole cage because a salesperson's script says so — he climbs it and tells you what is left.",
        "Holiday also generates steady calls for super gutters when oak litter and squall water overwhelm shallow builder troughs along the cage header. Bundle gutter work with rescreening so one ladder trip solves both problems instead of paying twice in the same season. Text wide shots and close-ups of tears, chalky mesh, or overflowing gutters to <a href=\"tel:7273866562\">(727) 386-6562</a>. Porch screens, window batches, and <a href=\"storm-screen-repair.html\">storm patches</a> after squalls still book on west Pasco loops alongside the main cage job when they meet the minimum.",
    ],
    "Holiday &amp; west Pasco waterfront neighborhoods",
    [
        ("<strong>Gulf Harbors</strong>", "canal homes, salt on lower panels, dock-side ladder access"),
        ("<strong>Anclote River streets</strong>", "wind off open water, roof panel tears after squalls"),
        ("<strong>Holiday Lake / Forest Hills</strong>", "1970s cages entering uniform oxidation"),
        ("<strong>Anclote Key adjacency</strong>", "coastal breeze fatigue on west-facing doors"),
        ("<strong>Tarpon Springs border</strong>", "paired routes with north Pinellas when scheduled"),
    ],
    "<strong>Home-base advantage:</strong> Holiday is among the fastest-scheduled cities we serve — see also <a href=\"new-port-richey-screen-repair.html\">New Port Richey</a> and <a href=\"hudson-screen-repair.html\">Hudson</a>.",
    "Priority work in Holiday: rescreens, new cages, super gutters",
    [
        "Full <a href=\"rescreens.html\">pool cage rescreens</a> restore tension across walls and roof horizontals when Holiday cages turn uniformly gray — common on 1980s–1990s stock in Forest Hills and canal subdivisions. Chris removes brittle mesh, checks aluminum for corrosion near water, and installs new screen with spline that survives the next Gulf season. Salt-damaged lower rows alone can quote separately when upper bays remain tight and feet are sound.",
        "Vacant waterfront lots and major rebuilds sometimes need a new enclosure rather than rescreening storm-compromised frames. Chris starts <a href=\"pool-enclosures.html\">new enclosure inquiries</a> and routes permits and engineering through licensed partners while staying your west Pasco contact. Canal setbacks, seawall access, and dock-side ladder setup get discussed before install day — no surprises for Gulf Harbors homeowners who need a partner path rather than a simple mesh swap.",
        "Super gutters matter on Holiday cages where leaves and squall water clog shallow troughs until overflow rots spline along the header. Ask about <a href=\"gutters-and-screens.html\">gutters and screens</a> and <a href=\"gutter-work.html\">gutter work</a> when rescreening — especially on Gulf Harbors homes with heavy canopy. Small jobs — lanai door patches, window screens, single storm panels — still qualify when they meet the minimum and ride the same NPR-area trip.",
    ],
    "Coastal Holiday weather on pool cages",
    [
        "Open water behind the lot means steady breeze that fatigues west-facing door spline and salt mist that chalks lower horizontals years before roofs fail inland. Chris inspects hardware and bottom rows first on canal homes; interior lots get roof horizontals checked first. After tropical systems, photograph every torn bay — partial <a href=\"storm-screen-repair.html\">storm repairs</a> often restore the cage when posts stay plumb.",
        "Afternoon Gulf squalls track into Holiday with wind that peels slack roof panels. Standing water on loose mesh accelerates the next tear — if the roof holds puddles after rain, rescreen season is closer than it looks. Pet doors on family cages get <a href=\"pet-resistant-screen-mesh.html\">pet-resistant mesh</a> when standard fiberglass fails after repeat patches.",
    ],
    [
        ("new-port-richey-screen-repair.html", "New Port Richey"),
        ("port-richey-screen-repair.html", "Port Richey"),
        ("hudson-screen-repair.html", "Hudson"),
        ("tarpon-springs-screen-repair.html", "Tarpon Springs"),
        ("pasco-county-screen-repair.html", "Pasco hub"),
        ("rescreens.html", "Rescreens"),
        ("gutters-and-screens.html", "Super gutters"),
        ("pool-enclosures.html", "New enclosures"),
        ("storm-screen-repair.html", "Storm repair"),
    ],
    [
        ("How fast can Holiday pool cage repair be scheduled?", "Often same-week from NPR — among our fastest west Pasco cities. Call (727) 386-6562 with photos."),
        ("Do you serve Gulf Harbors canal homes?", "Yes. Gulf Harbors and Anclote waterfront are core routes — mention dock or seawall access."),
        ("Can salt-damaged lower panels be replaced without a full rescreen?", "Often yes when upper mesh is tight and aluminum feet are sound — Chris quotes honestly from photos."),
        ("Do you install super gutters on Holiday pool cages?", "Yes. Oversized enclosure gutters are quoted with cage work — especially when troughs overflow."),
        ("Can you help with a new pool cage on a Holiday waterfront lot?", "New enclosure inquiries use our partner path for permits — start on pool enclosures and call Chris."),
    ],
    [
        ("<strong>Same-week potential</strong>", "Holiday often books faster than cross-county jobs — text photos early."),
        ("<strong>Dock / canal access</strong>", "Mention if ladders must set canal-side or near a seawall."),
        ("<strong>Photo gutters too</strong>", "If headers stay wet, include gutter overflow in your message."),
    ],
    "Holiday pool cage repair — west Pasco coast, minutes from home base.",
    [(G["pano2"], "Pool cage repair Holiday west Pasco coast"), (G["cage4"], "Lanai rescreen Gulf Harbors Holiday"), (G["side"], "Screen panel work Anclote area"), (G["door"], "Pool cage door repair Holiday Florida")],
    [(G["pano2"], "Coastal cage work — Holiday area"), (G["cage1"], "Pool enclosure repair — west Pasco")],
))

PASCO_CITIES.append(C(
    "hudson-screen-repair", "Hudson", PASCO, PASCO_L,
    "Lanai Screen Repair Hudson FL | Beacon Woods | Screen Team",
    "Lanai screen repair &amp; pool cage rescreens in Hudson, FL — Beacon Woods, Sea Pines &amp; north Pasco coast. Chris Westcott. (727) 386-6562.",
    "lanai screen repair Hudson FL, pool cage rescreen Hudson, screen repair Beacon Woods, porch screens north Pasco",
    "Lanai Screen Repair &amp; Pool Cage Rescreens in Hudson, FL",
    "North Pasco retirement communities and canal blocks — lanai doors, porch panels, and pool cages with Chris on every job.",
    "Hudson — Beacon Woods lanais, Sea Pines wind, lanai doors first",
    [
        "Hudson's identity is screened outdoor living — Beacon Woods, Sea Pines, and thousands of lanai-forward homes built for year-round Florida life where the door to the pool gets more traffic than the front entry. The dominant <strong>lanai screen repair Hudson FL</strong> call is not a catastrophic roof collapse; it is a door that drags on the track because spline failed on the hinge side while the mesh still looks fine from across the patio. Chris Westcott fixes doors first, inspects horizontals second, and quotes a full <a href=\"rescreens.html\">pool cage rescreen</a> only when oxidation is cage-wide — the honest sequence Hudson owners appreciate after decades of contractor upsells.",
        "North Pasco coastal influence reaches Hudson Beach and Sea Ridge canal streets where wind off open water stresses roof panels and salt mist chalks lower rows on waterfront lots. Inland Beacon Woods blocks see UV oxidation and pet abuse on the lanai door the dog uses every morning — the panel that fails is rarely random. Snowbird season spikes fall demand: owners want gray mesh replaced before guests arrive, and Chris schedules oxidation rescreens from photos when travelers are still up north.",
        "Hudson sits a short drive from New Port Richey home base, so west Pasco loops often include Hudson with NPR, Holiday, or Tarpon Springs when routing allows. That proximity is why lanai door calls here frequently land same-week — not because a call center promises it, but because Chris is already on your side of the county. Call or text <a href=\"tel:7273866562\">(727) 386-6562</a> with community name, especially in 55+ neighborhoods with contractor sign-in rules. Window screen batches and porch refreshes ride along when you are already booking lanai work.",
    ],
    "Hudson areas we work",
    [
        ("<strong>Beacon Woods</strong>", "lanai doors, porch refreshes, snowbird-season rescreens"),
        ("<strong>Sea Pines / Sea Ridge</strong>", "canal wind on roof panels, salt on lower rows"),
        ("<strong>Hudson Beach</strong>", "coastal exposure, hinge corrosion on waterfront doors"),
        ("<strong>SR-52 / US-19 corridor</strong>", "window screen batches between cage jobs"),
        ("<strong>Deer Island</strong>", "compact lanais, quick door and panel repairs"),
    ],
    "<strong>North Pasco note:</strong> Hudson pairs with <a href=\"new-port-richey-screen-repair.html\">New Port Richey</a> and <a href=\"tarpon-springs-screen-repair.html\">Tarpon Springs</a> on the same driving loop.",
    "Rescreens, new enclosures, and super gutters in Hudson",
    [
        "When Hudson cages turn uniformly chalky — common on 1980s stock entering its third decade — a full <a href=\"rescreens.html\">pool cage rescreen</a> replaces every wall and roof panel with properly tensioned mesh. Chris works bay by bay, checks door alignment on the lanai everyone actually uses, and finishes so latches catch clean. Partial quotes remain when only storm rows or a single abuse wall failed while the rest of the cage is sound.",
        "Major rebuilds and vacant lots in Hudson occasionally need a new enclosure instead of rescreening compromised aluminum. Chris opens <a href=\"pool-enclosures.html\">new enclosure inquiries</a> and coordinates partner-path permits while staying your north Pasco contact. Retirement-community rules, contractor sign-in at Beacon Woods gates, and snowbird access windows get handled with advance notice — not discovered when the truck arrives at the guardhouse.",
        "Leaf load from mature trees clogs shallow cage gutters until water rots header spline — super gutters and <a href=\"gutters-and-screens.html\">gutters and screens</a> bundles make sense during rescreen visits. <a href=\"gutter-work.html\">Gutter work</a> on the house tie-in can share the ladder setup. Small jobs — <a href=\"lanai-screen-replacement.html\">lanai replacement</a> on one door, window screens, porch panels — still book when they meet the minimum.",
    ],
    "North Pasco coastal vs community cages in Hudson",
    [
        "Canal and beach-adjacent Hudson lots see salt on lower horizontals and hinge corrosion on west-facing doors before inland Beacon Woods roofs fail. Chris adjusts inspection order accordingly. Open water wind peels slack roof panels after squalls — <a href=\"storm-screen-repair.html\">storm repairs</a> restore torn sections when posts remain plumb.",
        "Retirement-community lanais often fail at the door track first from daily use, not storm damage. If the latch will not catch, mention it when you call — hardware fixes are common. Fall oxidation rescreens peak before snowbird arrivals; book early if you want mesh refreshed before holiday guests.",
    ],
    [
        ("new-port-richey-screen-repair.html", "New Port Richey"),
        ("holiday-screen-repair.html", "Holiday"),
        ("tarpon-springs-screen-repair.html", "Tarpon Springs"),
        ("port-richey-screen-repair.html", "Port Richey"),
        ("pasco-county-screen-repair.html", "Pasco hub"),
        ("rescreens.html", "Rescreens"),
        ("lanai-screen-replacement.html", "Lanai replacement"),
        ("gutters-and-screens.html", "Super gutters"),
        ("pool-enclosures.html", "New enclosures"),
    ],
    [
        ("Do you repair lanai doors in Hudson?", "Yes. Door spline and latch alignment are the most common Hudson fixes — often before roof work."),
        ("Is Hudson close to your home base?", "Yes. Hudson is a short drive from New Port Richey for fast west Pasco scheduling."),
        ("Do you work in Beacon Woods and 55+ communities?", "Yes. Provide community name and any contractor sign-in procedures when booking."),
        ("Can you rescreen my pool cage before snowbird season?", "Yes. Fall oxidation rescreens are common — text photos early for best calendar access."),
        ("Do you install super gutters on Hudson lanais and cages?", "Yes when the header supports oversized troughs — quoted with rescreen or repair work."),
    ],
    [
        ("<strong>Name the community</strong>", "Beacon Woods, Sea Pines, etc. — helps gate and routing."),
        ("<strong>Book fall early</strong>", "Snowbird-season demand peaks — schedule lanai refreshes before November rush."),
        ("<strong>Bundle window screens</strong>", "Refresh lanai door and bedroom screens in one Hudson visit."),
    ],
    "Hudson lanai screen repair — north Pasco owner-direct, doors first.",
    [(G["lanai"], "Lanai screen repair Hudson Beacon Woods"), (G["porch"], "Screened porch Hudson north Pasco"), (G["cage2"], "Pool cage rescreen Sea Pines area"), (G["door"], "Lanai door spline Hudson FL")],
    [(G["porch"], "Lanai door repair — Hudson"), (G["cage3"], "Pool cage — north Pasco coast")],
))

PASCO_CITIES.append(C(
    "land-o-lakes-screen-repair", "Land O Lakes", PASCO, PASCO_L,
    "Screen Repair Land O Lakes FL | Connerton Cages | Screen Team",
    "Pool cage rescreen &amp; lanai repair in Land O Lakes, FL — Connerton, Oakstead &amp; east Pasco family pools. (727) 386-6562.",
    "screen repair Land O Lakes, pool cage rescreen Land O Lakes FL, lanai repair Connerton, pet door screen Land O Lakes",
    "Screen Repair &amp; Pool Cage Rescreens in Land O Lakes, FL",
    "Connerton, Oakstead, and east Pasco family pools — cages built for kids, dogs, and weekend cookouts.",
    "Land O Lakes — Connerton family cages, Oakstead oxidation, pet doors",
    [
        "Land O Lakes grew as east Pasco's family belt — Connerton, Oakstead, Wilderness Lake, and streets where every backyard seems to include a pool, a cage sized for summer birthdays, and a lanai door the dog treats like a personal exit. <strong>Screen repair Land O Lakes</strong> searches spike when school lets out and the weak panel finally gives way under teenager and Labrador traffic. Chris Westcott replaces abuse zones with <a href=\"pet-resistant-screen-mesh.html\">pet-resistant mesh</a> when standard fiberglass keeps failing, aligns latches that stopped catching because hinge-side spline gave up, and quotes full <a href=\"rescreens.html\">pool cage rescreens</a> when fifteen-year-old mesh turned chalky cage-wide.",
        "Master-planned communities mean predictable cage footprints but different maintenance clocks — rentals discovering torn spline before listing photos, year-round families hitting first oxidation on 2005-era stock, and HOAs that care about visibility from the street when mesh goes gray uniformly. Chris inspects the door everyone actually uses before quoting roof work, explains partial versus full scope without a sales script, and batches Land O Lakes with Wesley Chapel or Trinity on east Pasco days when geography allows efficient routing for everyone on the schedule.",
        "Collier Parkway corridor homes add lanai extensions tied to great rooms where builder spline pops within the first decade. Chris handles post-warranty cages daily — not a franchise crew learning your subdivision on the fly. Text community name, pet-traffic notes, and photos to <a href=\"tel:7273866562\">(727) 386-6562</a>. Window screen batches and porch tie-ins ride along when you are already booking cage work, and he will flag when a single abuse door upgrade beats another round of patches before summer break traffic starts.",
    ],
    "Land O Lakes communities &amp; cage types",
    [
        ("<strong>Connerton</strong>", "large family cages, pet-damaged doors, summer tear season"),
        ("<strong>Oakstead / Wilderness Lake</strong>", "first full rescreens on fifteen-year-old mesh"),
        ("<strong>Collier Parkway corridor</strong>", "lanai additions, porch tie-ins to great rooms"),
        ("<strong>Lutz border streets</strong>", "paired scheduling with north Hillsborough when routed"),
        ("<strong>Summertree / Tioga</strong>", "newer stock entering first oxidation wave"),
    ],
    "<strong>East Pasco:</strong> Land O Lakes routes with <a href=\"wesley-chapel-screen-repair.html\">Wesley Chapel</a> — mention both addresses if you manage rentals.",
    "Priority work in Land O Lakes: rescreens, new cages, super gutters",
    [
        "Full <a href=\"rescreens.html\">pool cage rescreens</a> land when Oakstead and Connerton cages show uniform oxidation — mesh that cracks under finger pressure on every wall, not just the dog door. Chris strips failed screen, verifies posts and headers on aluminum still square after a decade of Florida sun, and tension-tests roof panels so they stop holding puddles after afternoon storms. Door-only and lower-wall pet upgrades stay quoted separately when the rest of the cage has years left.",
        "Continuing build-out and tear-down rebuilds in Land O Lakes sometimes need a new enclosure rather than rescreening tired sections. Chris starts on <a href=\"pool-enclosures.html\">pool enclosures</a> and coordinates partner-path permits and engineering while staying your east Pasco contact. HOA height and visibility rules get discussed before anyone orders mesh — especially in Connerton and Oakstead where street-facing cages matter for curb appeal.",
        "Maturing street trees dump leaves into shallow cage gutters until overflow damages header spline — bundle <a href=\"gutters-and-screens.html\">gutters and screens</a> or <a href=\"gutter-work.html\">gutter work</a> with a rescreen when Chris is already on ladders. Small jobs — window screens, single storm panels, one lanai door — still qualify when they meet the minimum and share the east-county trip instead of waiting for a separate visit week.",
    ],
    "East Pasco family pools — wear patterns in Land O Lakes",
    [
        "Inland sun and afternoon storms age mesh without Gulf salt — roof horizontals fail first when tension drops, while abuse doors fail from pet and kid traffic regardless of roof condition. Chris checks the door panel everyone uses before assuming you need a full cage. After squalls, <a href=\"storm-screen-repair.html\">storm repairs</a> fix torn rows when posts stay plumb.",
        "Summer break accelerates damage on Connerton pools — book early June before tear season peaks. If one door panel fails repeatedly, pet-resistant upgrades on that leaf often outlast patching standard mesh every three months.",
    ],
    [
        ("wesley-chapel-screen-repair.html", "Wesley Chapel"),
        ("trinity-screen-repair.html", "Trinity"),
        ("odessa-screen-repair.html", "Odessa"),
        ("new-port-richey-screen-repair.html", "New Port Richey"),
        ("pasco-county-screen-repair.html", "Pasco hub"),
        ("rescreens.html", "Rescreens"),
        ("pet-resistant-screen-mesh.html", "Pet-resistant mesh"),
        ("pool-enclosures.html", "New enclosures"),
        ("gutters-and-screens.html", "Super gutters"),
    ],
    [
        ("Do you serve Land O Lakes and Connerton?", "Yes. Land O Lakes is core east Pasco within our service radius."),
        ("Can you upgrade a lanai door to pet mesh only?", "Yes. Door-only pet upgrades are common when the rest of the cage is still sound."),
        ("My Oakstead cage is fifteen years old — full rescreen?", "Often yes when oxidation is uniform — Chris inspects before quoting partial vs full."),
        ("Do you work on rental turnovers in Land O Lakes?", "Yes. Mention listing deadlines — partial jobs can precede photos."),
        ("Can you add super gutters during a Land O Lakes rescreen?", "Yes when the header supports oversized troughs — ask when booking."),
    ],
    [
        ("<strong>Name the community</strong>", "Connerton, Oakstead, etc. — speeds gate planning."),
        ("<strong>Which door has pet traffic?</strong>", "Chris upgrades the abuse panel when repeats fail."),
        ("<strong>Summer rush</strong>", "Book early June before school-out tear season fills the calendar."),
    ],
    "Land O Lakes screen repair — Connerton, Oakstead, east Pasco family routes.",
    [(G["cage1"], "Pool cage rescreen Land O Lakes Connerton"), (G["mesh"], "Pet door mesh upgrade Land O Lakes"), (G["cage3"], "Family pool enclosure Oakstead"), (G["rescreen"], "Full cage refresh east Pasco")],
    [(G["cage1"], "Cage rescreen — Land O Lakes"), (G["done"], "Completed enclosure — east Pasco")],
))

PASCO_CITIES.append(C(
    "wesley-chapel-screen-repair", "Wesley Chapel", PASCO, PASCO_L,
    "Screen Enclosures Wesley Chapel FL | Wiregrass | Screen Team",
    "Screen enclosures &amp; pool cage rescreen in Wesley Chapel, FL — Wiregrass, Seven Oaks &amp; builder mesh upgrades. (727) 386-6562.",
    "screen repair Wesley Chapel FL, pool cage rescreen Wesley Chapel, screen enclosures Wiregrass, lanai repair east Pasco",
    "Screen Enclosures &amp; Pool Cage Rescreens in Wesley Chapel, FL",
    "Wiregrass, Seven Oaks, and east Pasco master-planned cages — builder mesh aging out, first rescreens, and honest upgrade paths.",
    "Wesley Chapel — Wiregrass growth, Seven Oaks height, builder mesh limits",
    [
        "Wesley Chapel enclosures are younger than west Pasco canal stock but Florida UV does not grant exemptions — builder-grade mesh on Wiregrass and Seven Oaks cages turns chalky within a decade, and lanai doors lose spline on the hinge side while walls still look presentable from the curb. <strong>Screen repair Wesley Chapel FL</strong> searches often come from homeowners discovering their first uniform oxidation wave, not storm catastrophe. Chris Westcott replaces what failed, tells you if the whole cage is nearing rescreen age, and explains mesh upgrade options without pushing visibility fiberglass you did not ask for.",
        "Two-story cages off SR-54 and in Seven Oaks add height and ladder planning that per-panel quotes ignore until install day. Chris prices access upfront from photos showing the cage relative to the roofline — no surprise scaffolding fees when he arrives on a Wiregrass cul-de-sac. Chapel Pines and Meadow Pointe border homes bring lanai extensions off great rooms where builder spline popped within the first five years; door alignment and hinge-side replacement are common first-year fixes after the builder warranty expires.",
        "East Pasco routing batches Wesley Chapel with Land O Lakes or Zephyrhills on the same day when geography allows. Text subdivision name, gate instructions, and whether you are pre-listing a rental to <a href=\"tel:7273866562\">(727) 386-6562</a>. First-time <a href=\"rescreens.html\">pool cage rescreens</a> here are a chance to pick pet doors, clearer mesh, or standard fiberglass at line-item prices before the next dog season — Chris explains the delta without pushing upgrades you did not ask for on the written quote.",
    ],
    "Wesley Chapel communities",
    [
        ("<strong>Wiregrass / Tampa Premium area</strong>", "family pools, pet-damaged door panels, newer oxidation"),
        ("<strong>Seven Oaks</strong>", "two-story cages, ladder access planning, upper roof rows"),
        ("<strong>Chapel Pines / Meadow Pointe border</strong>", "lanai extensions off great rooms, builder spline issues"),
        ("<strong>SR-54 corridor</strong>", "quick window screen batches between cage jobs"),
        ("<strong>Epperson / Epperson Ranch</strong>", "lagoon-community cages, first-decade maintenance"),
    ],
    "<strong>East Pasco routing:</strong> Wesley Chapel pairs with <a href=\"land-o-lakes-screen-repair.html\">Land O Lakes</a> — mention both properties if you manage rentals.",
    "Rescreens, new enclosures, and super gutters in Wesley Chapel",
    [
        "First full <a href=\"rescreens.html\">pool cage rescreens</a> on Wesley Chapel builder cages restore tension before slack roof panels hold standing water and unzip in the next afternoon storm. Chris removes uniformly oxidized mesh, checks posts and headers on aluminum still in good shape, and finishes the lanai door everyone uses daily. Partial quotes stay available when only the abuse panel and one wall show wear — common in Wiregrass homes with active dogs.",
        "New construction pads and major rebuilds in continuing Wesley Chapel development sometimes need a partner-path enclosure instead of rescreening. Chris starts on <a href=\"pool-enclosures.html\">pool enclosures</a> and coordinates permits and engineering through licensed partners while remaining your east Pasco contact. HOA design rules, height limits, and visibility from the street get discussed before mesh orders — especially in master-planned phases where enclosure aesthetics matter to the association.",
        "Maturing landscaping clogs shallow builder gutters until overflow damages header spline — super gutters and <a href=\"gutters-and-screens.html\">gutters and screens</a> bundles make sense during your first rescreen. <a href=\"gutter-work.html\">Gutter work</a> on the house connection can share the visit. Small jobs — window screens, single panels, porch patches — still book when they meet the minimum alongside cage work instead of waiting for a separate trip across east Pasco.",
    ],
    "Builder mesh and inland storms on Wesley Chapel cages",
    [
        "Without coastal salt, Wesley Chapel cages fail from UV and inland thunderstorm wind on roof horizontals first. Builder mesh that looked tight at closing turns gray uniformly — patching one bay on chalky neighbors is a short-term fix Chris will flag honestly. Seven Oaks two-story cages need upper-row attention when slack panels hold puddles after rain.",
        "After named storms, <a href=\"storm-screen-repair.html\">storm repairs</a> restore torn sections when frames stay plumb. Pet abuse on the lanai door gets <a href=\"pet-resistant-screen-mesh.html\">pet-resistant mesh</a> on that leaf when standard fiberglass fails every few months. Closing soon? Mention timeline — partial door work can precede listing photos.",
    ],
    [
        ("land-o-lakes-screen-repair.html", "Land O Lakes"),
        ("zephyrhills-screen-repair.html", "Zephyrhills"),
        ("trinity-screen-repair.html", "Trinity"),
        ("tampa-screen-repair.html", "Tampa"),
        ("pasco-county-screen-repair.html", "Pasco hub"),
        ("rescreens.html", "Rescreens"),
        ("pool-enclosures.html", "New enclosures"),
        ("gutters-and-screens.html", "Super gutters"),
        ("screen-panel-repair.html", "Panel repair"),
    ],
    [
        ("Is Wesley Chapel in your service area?", "Yes. East Pasco including Wesley Chapel is within our typical coverage."),
        ("My builder mesh is only eight years old — why is it failing?", "Florida UV ages standard builder mesh faster than northern climates. Chris inspects before quoting full vs partial."),
        ("Do you work on two-story cages in Seven Oaks?", "Yes. Height and ladder access are priced upfront from elevation photos."),
        ("Can I upgrade mesh during my first Wesley Chapel rescreen?", "Yes. Pet, visibility, and standard options are line-item priced — you choose before install."),
        ("Do you handle new screened enclosures on new builds?", "New enclosure inquiries use our partner path when permits apply — start on pool enclosures."),
    ],
    [
        ("<strong>Subdivision gate info</strong>", "Wiregrass, Seven Oaks, etc. — provide community name and access."),
        ("<strong>Builder warranty expired?</strong>", "Chris handles post-warranty cages daily — note approximate cage age."),
        ("<strong>Closing timeline</strong>", "Mention if listing photos depend on lanai door repair soon."),
    ],
    "Wesley Chapel screen enclosures — Wiregrass, Seven Oaks, builder mesh done right.",
    [(G["preview"], "Screen enclosure Wesley Chapel Wiregrass"), (G["cage3"], "Pool cage repair Seven Oaks area"), (G["lanai"], "Lanai screen work east Pasco"), (G["tall"], "Two-story cage Wesley Chapel FL")],
    [(G["cage2"], "Enclosure rescreen — Wesley Chapel"), (G["rescreen"], "Pool cage refresh — east Pasco")],
))
