#!/usr/bin/env python3
"""Hillsborough County city geo content for Screen Team SEO pages."""
from geo_content import C, G, HILL, HILL_L

HILLSBOROUGH_CITIES = []

HILLSBOROUGH_CITIES.append(C(
    "tampa-screen-repair", "Tampa", HILL, HILL_L,
    "Screen Repair Tampa FL | Pool Cage Rescreen &amp; Super Gutters | Screen Team",
    "Full pool cage rescreen, new enclosure inquiries &amp; super gutters in Tampa, FL. Owner Chris Westcott crosses from NPR. (727) 386-6562.",
    "screen repair Tampa FL, pool cage rescreen Tampa, tall pool cage Tampa, lanai screen repair Hillsborough, super gutters Tampa",
    "Screen Repair, Pool Cages &amp; Super Gutters in Tampa, FL",
    "Hillsborough's largest city — South Tampa lanais, New Tampa tall cages, Carrollwood oaks, and Westchase family pools. Chris Westcott rescreens, repairs, and routes new-enclosure inquiries from New Port Richey with travel confirmed upfront.",
    "Tampa — cross-bay cage work from South Tampa to New Tampa",
    [
        "Tampa is not one enclosure market — it is a county-sized spread of cage styles. <strong>South Tampa</strong> favors compact lanais and porch screens tucked behind brick streets where oak limbs scrape roof panels every summer. <strong>New Tampa</strong> and the I-275 corridor north of the city center brought two-story cages and 18-foot side walls during the 2000s building wave. <strong>Carrollwood</strong> and <strong>Westchase</strong> sit between those worlds: mature canopy, 1980s–2000s aluminum, and family pools that need honest tall-cage quotes instead of single-story pricing surprises.",
        "Screen Team LLC is based in New Port Richey — Tampa jobs are a confirmed cross-bay route, not a vague service-area promise. When you search <strong>screen repair Tampa FL</strong>, you usually need a straight answer: storm tear on a roof horizontal, chalky mesh cage-wide, a dog-destroyed door panel, or a conversation about a brand-new enclosure on a pad that never had a cage. Chris Westcott handles rescreens and repairs owner-direct and opens the licensed partner path when permits and engineering are required.",
        "Text photos to <a href=\"tel:7273866562\">(727) 386-6562</a> with your neighborhood — Hyde Park, Westshore, Forest Hills, Hunter's Green, or anywhere the zip confirms Hillsborough coverage. Chris will tell you whether a partial <a href=\"pool-cage-repair.html\">pool cage repair</a> makes sense, whether a full <a href=\"rescreens.html\">pool cage rescreen</a> is the honest fix, and whether your gutter line needs attention before new mesh goes up.",
    ],
    "Tampa neighborhoods &amp; enclosure types",
    [
        ("<strong>South Tampa / Hyde Park corridor</strong>", "compact lanais, porch screens, historic-lot access"),
        ("<strong>New Tampa / Hunters Green</strong>", "tall two-story cages, wind-loaded roof rows"),
        ("<strong>Carrollwood / Northdale</strong>", "oak debris on roof panels, 1990s cage stock"),
        ("<strong>Westchase / Citrus Park edge</strong>", "family pools, pet-damaged door panels"),
        ("<strong>Forest Hills / Seminole Heights border</strong>", "older ranch cages, mixed partial vs full rescreen calls"),
    ],
    "<strong>Cross-bay scheduling:</strong> Tampa routes from NPR are confirmed when you call — not assumed. Pair with <a href=\"brandon-screen-repair.html\">Brandon</a>, <a href=\"carrollwood-screen-repair.html\">Carrollwood</a>, or <a href=\"town-n-country-screen-repair.html\">Town 'n' Country</a> when multiple Hillsborough addresses need work.",
    "Priority work: full rescreens, new enclosure inquiries, super gutters",
    [
        "Full pool cage rescreens are the core Tampa call once mesh turns chalky on every wall — especially on tall New Tampa cages where upper roof horizontals fail before lower panels look bad. Chris strips oxidized screen, checks posts and doors, and rolls new mesh with proper spline tension. If only a roof row or abuse door failed, he quotes a partial instead of upselling the whole cage.",
        "Need a <em>new</em> pool enclosure or structural rebuild on a vacant pad? Screen Team routes those inquiries through licensed contractor partners when Hillsborough engineering stamps or permits are required. Chris remains your local contact — start on <a href=\"pool-enclosures.html\">pool enclosures</a> and he will tell you what the partner path covers versus what a rescreen on existing aluminum can solve.",
        "Super gutters and oversized enclosure gutters matter where Tampa oak canopy dumps leaves into shallow troughs along the cage header. Overflow stains fascia, soaks spline at the top plate, and accelerates the next roof tear. Ask about <a href=\"gutters-and-screens.html\">gutters and screens</a> when water sheets off the cage roof after every squall. Window screens, single panels, and <a href=\"storm-screen-repair.html\">storm patches</a> still book alongside the big work.",
    ],
    "Hillsborough weather on Tampa cages",
    [
        "Inland Tampa heat and afternoon thunder hit cages harder than many homeowners expect — UV brittles roof mesh while sudden gusts peel slack horizontals before side walls show wear. Bay-adjacent pockets near Westshore and the airport corridor add humidity that keeps spline soft longer but does not stop oxidation. Chris replaces torn sections when aluminum is still plumb; uniform gray mesh that snaps in your fingers usually means a full rescreen is the honest fix.",
        "Oak litter from Carrollwood and South Tampa streets collects on shallow gutter lines and rots spline at the header. If the latch will not catch but mesh looks fine, the door panel is often first. Family cages in Westchase and New Tampa get <a href=\"pet-resistant-screen-mesh.html\">pet-resistant mesh</a> on the abuse door when standard fiberglass keeps failing after one summer.",
    ],
    [
        ("brandon-screen-repair.html", "Brandon"),
        ("carrollwood-screen-repair.html", "Carrollwood"),
        ("town-n-country-screen-repair.html", "Town 'n' Country"),
        ("riverview-screen-repair.html", "Riverview"),
        ("citrus-park-screen-repair.html", "Citrus Park"),
        ("temple-terrace-screen-repair.html", "Temple Terrace"),
        ("hillsborough-county-screen-repair.html", "Hillsborough hub"),
        ("rescreens.html", "Rescreens"),
        ("pool-enclosures.html", "New enclosures"),
        ("gutters-and-screens.html", "Super gutters"),
    ],
    [
        ("Does Screen Team serve Tampa from New Port Richey?", "Yes. Tampa is a regular Hillsborough route — Chris confirms travel and neighborhood coverage when you call (727) 386-6562."),
        ("Can you rescreen a tall two-story cage in New Tampa?", "Yes, when access and frame condition allow. Height is priced into the quote from photos — not discovered after the ladder is up."),
        ("Do you help with brand-new pool enclosures in Tampa?", "New enclosure inquiries go through a licensed partner path when permits and engineering are required. Chris stays your local contact."),
        ("Are super gutters available on older Tampa cages?", "Yes. Oversized enclosure gutters are quoted with cage work when headers can support them — especially under heavy oak canopy."),
        ("Is there a travel charge for cross-bay Tampa jobs?", "Chris discusses travel and full scope upfront. You know the price before appointment day — no surprise add-ons on site."),
    ],
    [
        ("<strong>Name your neighborhood</strong>", "South Tampa, New Tampa, Carrollwood, and Westchase access differ — zip and street context help."),
        ("<strong>Photo roof + door</strong>", "Tall cages fail at the header first. Wide shot plus close-ups speed the quote."),
        ("<strong>Confirm travel day</strong>", "Hillsborough routes batch from NPR — Chris locks your window when you book."),
    ],
    "Tampa screen repair — cross-bay owner-direct from Chris Westcott.",
    [
        (G["tall"], "Tall pool cage rescreen Tampa New Tampa"),
        (G["pano1"], "Pool enclosure panorama Hillsborough"),
        (G["cage2"], "Lanai screen repair Tampa FL"),
        (G["door"], "Pool cage door spline Tampa"),
    ],
    [
        (G["rescreen"], "Full cage rescreen — Tampa Hillsborough"),
        (G["done"], "Completed pool enclosure — Tampa"),
    ],
))

HILLSBOROUGH_CITIES.append(C(
    "brandon-screen-repair", "Brandon", HILL, HILL_L,
    "Screen Repair Brandon FL | Pool Cage Rescreen &amp; Tall Cages | Screen Team",
    "Pool cage rescreen, lanai repair &amp; super gutters in Brandon, FL. East Hillsborough storms, Bloomingdale cages. Chris Westcott. (727) 386-6562.",
    "screen repair Brandon FL, pool cage rescreen Brandon, Bloomingdale screen repair, FishHawk screen repair, tall pool cage Brandon",
    "Screen Repair, Pool Cages &amp; Super Gutters in Brandon, FL",
    "East Hillsborough's hub — Bloomingdale oaks, FishHawk border growth, and tall cages that take Gulf-fed storm bands before the rain reaches the bay. Full rescreens, partner-path new enclosures, and super gutters from Chris Westcott.",
    "Brandon — east Hillsborough storms and tall family cages",
    [
        "Brandon sits inland enough to feel like classic Florida suburbia — wide lots, HOA pools, and cages that went up during the 1990s and 2000s building waves. <strong>Bloomingdale</strong> and the <strong>FishHawk Ranch</strong> border bring master-planned streets where two-story cages and 16-foot side walls are normal, not exceptions. When mesh turns chalky cage-wide or a summer squall peels a roof horizontal, homeowners search <strong>screen repair Brandon FL</strong> and need someone who prices height honestly.",
        "East Hillsborough storm tracks hit Brandon before they weaken over the bay. Afternoon cells roll off the interior and load wind onto roof panels while oak limbs from Bloomingdale canopy punch holes in lower bays. Chris Westcott inspects whether aluminum is still square — partial <a href=\"pool-cage-repair.html\">pool cage repair</a> when one zone failed, full <a href=\"rescreens.html\">rescreen</a> when oxidation is uniform across every wall.",
        "Screen Team routes Brandon from New Port Richey with travel confirmed at booking — often paired with <a href=\"valrico-screen-repair.html\">Valrico</a> or <a href=\"riverview-screen-repair.html\">Riverview</a> on the same Hillsborough day. Text photos to <a href=\"tel:7273866562\">(727) 386-6562</a> and Chris will outline partial versus full scope, tall-cage access needs, and whether your header gutter should be addressed before new mesh goes up.",
    ],
    "Brandon neighborhoods &amp; enclosure types",
    [
        ("<strong>Bloomingdale / Bloomingdale East</strong>", "mature oaks, 1990s tall cages, leaf-clogged gutters"),
        ("<strong>FishHawk border / Lithia adjacency</strong>", "newer subdivisions, family pools, pet-damaged doors"),
        ("<strong>Brandon Town Center corridor</strong>", "mixed-age cages, lanai and porch screen batches"),
        ("<strong>Providence Lakes / Lake Brandon</strong>", "wind-exposed roof rows after east-side storms"),
        ("<strong>Seffner border streets</strong>", "ranch cages, honest partial-vs-full rescreen calls"),
    ],
    "<strong>East Hillsborough loop:</strong> Brandon batches with <a href=\"valrico-screen-repair.html\">Valrico</a>, <a href=\"riverview-screen-repair.html\">Riverview</a>, and <a href=\"plant-city-screen-repair.html\">Plant City</a> when schedules align — mention multiple addresses when you call.",
    "Priority work: full rescreens, new enclosure inquiries, super gutters",
    [
        "Full pool cage rescreens dominate Brandon calls once every wall feels brittle — especially on tall Bloomingdale cages where upper horizontals failed years before the lower mesh looked bad. Chris removes failed screen, verifies posts and kick plates, and installs new mesh with tension that survives the next east-side storm season. Partial quotes stay on the table when only a roof row or door needs work.",
        "Building a new cage on a Brandon lot or replacing storm-damaged structure? Screen Team opens <a href=\"pool-enclosures.html\">new enclosure inquiries</a> through licensed partners when Hillsborough permits and engineering are part of the job. Chris remains the owner you text — he scopes photos, explains the partner path, and stays involved through install coordination.",
        "Super gutters solve the Brandon pattern of oak litter filling shallow troughs along the cage header. Water overflows onto spline, stains fascia, and shortens mesh life along the top plate. Pair <a href=\"gutters-and-screens.html\">gutters and screens</a> with a rescreen so you are not climbing twice. Smaller jobs — window screens, porch panels, <a href=\"lanai-screen-replacement.html\">lanai replacement</a> — ride along on the same confirmed travel day.",
    ],
    "East Hillsborough weather on Brandon cages",
    [
        "Inland thunder cells build heat over Brandon afternoons and unload on roof horizontals before homeowners finish dinner. UV still chalks mesh on south-facing walls, but wind-driven rain from the east is what unzips slack roof panels. Chris patches storm tears when posts are plumb; chalky cage-wide oxidation means a full rescreen is the durable answer.",
        "Bloomingdale oak debris collects in gutter lines and rots spline at the header faster than open-lot cages in newer FishHawk-border subdivisions. Dog-torn lower panels on family pools are common — <a href=\"pet-resistant-screen-mesh.html\">pet-resistant mesh</a> on the abuse door often outlasts repeated fiberglass replacements.",
    ],
    [
        ("valrico-screen-repair.html", "Valrico"),
        ("riverview-screen-repair.html", "Riverview"),
        ("tampa-screen-repair.html", "Tampa"),
        ("plant-city-screen-repair.html", "Plant City"),
        ("seffner-screen-repair.html", "Seffner"),
        ("hillsborough-county-screen-repair.html", "Hillsborough hub"),
        ("rescreens.html", "Rescreens"),
        ("pool-enclosures.html", "New enclosures"),
        ("gutters-and-screens.html", "Super gutters"),
        ("storm-screen-repair.html", "Storm repair"),
    ],
    [
        ("Do you serve Brandon and Bloomingdale?", "Yes. Brandon is a core east Hillsborough route — Chris confirms travel from NPR when you book."),
        ("Can you rescreen tall cages near FishHawk?", "Yes. Height and ladder access are priced from photos — Bloomingdale and FishHawk-border tall cages are regular work."),
        ("How do east Hillsborough storms affect my cage?", "Wind loads roof panels first. After a cell, photograph torn bays before calling — partial repair is often enough when aluminum is sound."),
        ("Do you handle new pool enclosures in Brandon?", "New builds use the licensed partner path on <a href=\"pool-enclosures.html\">pool enclosures</a> when permits are required. Chris starts the conversation."),
        ("Are super gutters worth it under Bloomingdale oaks?", "Often yes. Leaf litter in shallow gutters soaks the header spline — oversized enclosure gutters are quoted with cage work."),
    ],
    [
        ("<strong>Note Bloomingdale vs FishHawk</strong>", "Canopy and cage height differ — neighborhood helps scope tall work."),
        ("<strong>Photo after east-side storms</strong>", "Roof horizontals fail first. Wide plus close-up shots speed quotes."),
        ("<strong>Bundle gutter check</strong>", "If water sheets off the cage roof, mention super gutters when booking."),
    ],
    "Brandon screen repair — east Hillsborough owner-direct service.",
    [
        (G["cage3"], "Tall pool cage Brandon Bloomingdale"),
        (G["pano2"], "Pool enclosure rescreen east Hillsborough"),
        (G["lanai"], "Lanai screen repair Brandon FL"),
        (G["work"], "Screen enclosure work Brandon"),
    ],
    [
        (G["cage4"], "Pool cage repair — Brandon"),
        (G["mesh"], "New mesh installation Brandon Hillsborough"),
    ],
))

HILLSBOROUGH_CITIES.append(C(
    "carrollwood-screen-repair", "Carrollwood", HILL, HILL_L,
    "Screen Repair Carrollwood FL | Pool Cage Rescreen &amp; Oak Canopy | Screen Team",
    "Pool cage rescreen, lanai repair &amp; super gutters in Carrollwood, FL. Mature oaks, 80s–2000s cages. Chris Westcott. (727) 386-6562.",
    "screen repair Carrollwood FL, pool cage rescreen Carrollwood, Northdale screen repair, Carrollwood Village screen enclosure",
    "Screen Repair, Pool Cages &amp; Super Gutters in Carrollwood, FL",
    "Established north Tampa suburb — mature live oaks, Carrollwood Village pools, and 1980s–2000s cages that need gutter-smart rescreens. Chris Westcott crosses from NPR with travel confirmed.",
    "Carrollwood — north Tampa oaks and decades of cage stock",
    [
        "Carrollwood is the north Tampa address people mean when they say established suburb: tree-lined streets, Carrollwood Village shopping corridors, and pool cages that went up across the 1980s, 1990s, and early 2000s. Mature live oaks drop limbs and leaves onto roof panels year-round — shallow gutter lines clog fast, spline at the header rots, and homeowners search <strong>screen repair Carrollwood FL</strong> when the cage still looks structurally fine but mesh is failing everywhere at once.",
        "Northdale and Carrollwood Country Club pockets mix ranch cages with taller two-story enclosures near newer infill. Chris Westcott knows the difference between a storm tear on one roof horizontal and oxidation that means a full <a href=\"rescreens.html\">pool cage rescreen</a>. He quotes partial <a href=\"pool-cage-repair.html\">pool cage repair</a> when aluminum is sound and does not upsell a complete job when one door panel or dog-torn lower bay is the real problem.",
        "Screen Team schedules Carrollwood from New Port Richey — often the same Hillsborough day as <a href=\"citrus-park-screen-repair.html\">Citrus Park</a>, <a href=\"lutz-screen-repair.html\">Lutz</a>, or <a href=\"tampa-screen-repair.html\">Tampa</a> north-side routes. Text photos to <a href=\"tel:7273866562\">(727) 386-6562</a> with oak-canopy context and Chris will flag whether super gutters should be part of the rescreen conversation.",
    ],
    "Carrollwood neighborhoods &amp; enclosure types",
    [
        ("<strong>Carrollwood Village / Northdale</strong>", "1990s cages, oak debris on roof rows"),
        ("<strong>Carrollwood Country Club area</strong>", "golf-community pools, lanai door wear"),
        ("<strong>Lake Carroll / pond lots</strong>", "humidity on lower panels, hardware checks"),
        ("<strong>Dale Mabry north corridor</strong>", "mixed porch screens and mid-size cages"),
        ("<strong>Citrus Park border</strong>", "family pools paired with shopping-corridor routes"),
    ],
    "<strong>North Tampa loop:</strong> Carrollwood pairs with <a href=\"citrus-park-screen-repair.html\">Citrus Park</a>, <a href=\"lutz-screen-repair.html\">Lutz</a>, and north <a href=\"tampa-screen-repair.html\">Tampa</a> when Chris batches a Hillsborough day from NPR.",
    "Priority work: full rescreens, new enclosure inquiries, super gutters",
    [
        "Full pool cage rescreens are the honest Carrollwood call when mesh is chalky on every wall — common on 1990s stock that never got a gutter upgrade. Chris strips failed screen, checks posts and doors, and installs new mesh with tension that survives oak-litter seasons. Partial work stays on the table when only the roof row under the canopy failed.",
        "Replacing a collapsed cage or building on a cleared lot near Carrollwood Country Club? Screen Team routes <a href=\"pool-enclosures.html\">new enclosure inquiries</a> through licensed partners when Hillsborough permits and engineering apply. Chris scopes your pad, explains the partner path, and remains your local owner contact.",
        "Super gutters matter under Carrollwood oaks more than almost anywhere in Hillsborough. Undersized troughs overflow, soak spline at the header, and stain fascia before mesh tears. Ask about <a href=\"gutters-and-screens.html\">gutters and screens</a> during the rescreen quote — pairing both avoids a second ladder trip six months later.",
    ],
    "Oak canopy and inland heat on Carrollwood cages",
    [
        "Carrollwood is inland Tampa Bay — afternoon thunder and UV dominate over salt spray. Oak limbs scar roof panels; accumulated leaves accelerate gutter failure along the cage header. Chris replaces storm tears when posts are plumb; uniform brittle mesh across all bays means rescreen the whole cage.",
        "Humidity on pond-adjacent lots keeps spline soft longer but does not stop oxidation on south-facing walls. Door panels fail first when latches drift — if mesh looks fine but the cage will not close, the door bay is often the fix, not a full rescreen.",
    ],
    [
        ("citrus-park-screen-repair.html", "Citrus Park"),
        ("lutz-screen-repair.html", "Lutz"),
        ("tampa-screen-repair.html", "Tampa"),
        ("town-n-country-screen-repair.html", "Town 'n' Country"),
        ("temple-terrace-screen-repair.html", "Temple Terrace"),
        ("hillsborough-county-screen-repair.html", "Hillsborough hub"),
        ("rescreens.html", "Rescreens"),
        ("gutters-and-screens.html", "Super gutters"),
        ("pool-enclosures.html", "New enclosures"),
        ("lanai-screen-replacement.html", "Lanai replacement"),
    ],
    [
        ("Do you serve Carrollwood and Northdale?", "Yes. Carrollwood is a regular north Tampa Hillsborough route — travel confirmed from NPR at booking."),
        ("Why do Carrollwood cages fail at the gutter line?", "Oak litter clogs shallow troughs. Water soaks spline at the header — super gutters are often the long-term fix."),
        ("Can you rescreen 1990s Carrollwood cages without replacing aluminum?", "Yes. Rescreening replaces mesh and spline on sound frames — Chris inspects posts before quoting."),
        ("Do you handle new enclosures in Carrollwood?", "New builds use the partner path on <a href=\"pool-enclosures.html\">pool enclosures</a> when permits are required."),
        ("How far in advance should I book Carrollwood work?", "Hillsborough days batch from New Port Richey — call early in the week for the best travel-window fit."),
    ],
    [
        ("<strong>Mention oak canopy</strong>", "Heavy tree cover changes gutter and roof-panel wear — note it when texting photos."),
        ("<strong>Photo the header line</strong>", "Gutter overflow stains are a clue — close-ups help Chris recommend super gutters."),
        ("<strong>Confirm north Tampa zip</strong>", "Carrollwood, Northdale, and Citrus Park border — zip speeds routing."),
    ],
    "Carrollwood screen repair — oak-smart rescreens from Chris Westcott.",
    [
        (G["porch"], "Porch and lanai screen Carrollwood"),
        (G["cage1"], "Pool cage rescreen Carrollwood FL"),
        (G["side"], "Screen enclosure panels north Tampa"),
        (G["preview"], "Pool enclosure preview Carrollwood"),
    ],
    [
        (G["pano3"], "Panorama pool cage Carrollwood"),
        (G["tall"], "Tall enclosure rescreen Carrollwood"),
    ],
))

HILLSBOROUGH_CITIES.append(C(
    "town-n-country-screen-repair", "Town 'n' Country", HILL, HILL_L,
    "Screen Repair Town 'n' Country FL | Pool Cage &amp; Lanai | Screen Team",
    "Pool cage rescreen, lanai repair &amp; super gutters in Town 'n' Country, FL. West Hillsborough cages, hurricane-season wear. (727) 386-6562.",
    "screen repair Town n Country FL, pool cage rescreen Town n Country, west Hillsborough screen repair, lanai repair Town n Country",
    "Screen Repair, Pool Cages &amp; Super Gutters in Town 'n' Country, FL",
    "West Hillsborough between Tampa Bay and inland heat — older enclosures, veteran-lot lanais, and hurricane-season roof rows. Full rescreens, new-enclosure partner path, and super gutters from Chris Westcott.",
    "Town 'n' Country — west Hillsborough between bay breeze and inland storms",
    [
        "<strong>Town 'n' Country</strong> stretches along the west side of Hillsborough — close enough to Old Tampa Bay that some lots catch bay humidity and breeze, far enough inland that afternoon thunder still hammers roof panels the same way it does in Brandon. Housing stock skews older: ranch pools, shallow gutter lines, and cages that have been patched panel-by-panel through multiple hurricane seasons. Homeowners search <strong>screen repair Town 'n' Country FL</strong> when mesh is chalky cage-wide or when Irma-era damage was never fully resolved.",
        "Westshore-adjacent streets and the Hillsborough Avenue corridor mix compact lanais with full pool cages behind 1970s–1990s homes. Chris Westcott inspects whether aluminum feet show corrosion on bay-influenced lots versus inland UV chalking on east-side pockets near Citrus Park Road. Partial <a href=\"pool-cage-repair.html\">pool cage repair</a> when one zone failed; full <a href=\"rescreens.html\">rescreen</a> when every wall tells the same oxidation story.",
        "Screen Team crosses from New Port Richey — Town 'n' Country routes confirm travel at booking, often paired with <a href=\"citrus-park-screen-repair.html\">Citrus Park</a> or <a href=\"tampa-screen-repair.html\">Tampa</a> west-side work. Text photos to <a href=\"tel:7273866562\">(727) 386-6562</a> and note whether your lot feels bay-adjacent or fully inland — Chris adjusts the inspection focus accordingly.",
    ],
    "Town 'n' Country neighborhoods &amp; enclosure types",
    [
        ("<strong>Bay-adjacent west pockets</strong>", "humidity on lower panels, hardware corrosion checks"),
        ("<strong>Hillsborough Ave / Hanley corridor</strong>", "ranch cages, porch and lanai screen batches"),
        ("<strong>Town 'n' Country Boulevard area</strong>", "older enclosures, hurricane-season roof repairs"),
        ("<strong>Citrus Park border</strong>", "mixed-age cages on west Hillsborough loop days"),
        ("<strong>Westshore adjacency</strong>", "compact lanais, door spline failure from bay humidity"),
    ],
    "<strong>West Hillsborough note:</strong> Bay-adjacent lots see humidity on lower mesh; inland pockets skew toward UV and thunder damage. Chris confirms your sub-area when quoting.",
    "Priority work: full rescreens, new enclosure inquiries, super gutters",
    [
        "Full pool cage rescreens are the core Town 'n' Country call once mesh turns brittle on every wall — especially on cages that survived multiple hurricane seasons with only partial patches. Chris strips failed screen, verifies the frame, and installs new mesh with proper tension. He quotes partial work when a single roof row or door is the isolated failure.",
        "Need a new pool enclosure on a west Hillsborough lot or replacing storm-collapsed structure? Screen Team opens <a href=\"pool-enclosures.html\">new enclosure inquiries</a> through licensed partners when permits and engineering are required. Chris stays your owner contact from first photos through partner coordination.",
        "Super gutters and oversized enclosure gutters matter where shallow troughs overflow during summer squalls — common on older Town 'n' Country headers. Pair <a href=\"gutters-and-screens.html\">gutters and screens</a> with a rescreen before the next hurricane season loads debris onto slack roof panels. Window screens and <a href=\"storm-screen-repair.html\">storm patches</a> book on the same confirmed travel day.",
    ],
    "Bay-adjacent humidity vs inland thunder on Town 'n' Country cages",
    [
        "Lots near Old Tampa Bay catch humidity that softens spline and stains lower horizontals — Chris checks hardware on west-facing bays first. Inland pockets east of the main corridors see harder UV and thunder gusts that peel roof panels before side walls fail. After named storms, photograph every torn bay — partial repair restores sound aluminum without a full rescreen.",
        "Hurricane-season debris loads roof rows on older enclosures that never got gutter upgrades. If water sheets off the cage header after every rain, super gutters are often the fix that extends the next mesh cycle — not another patch on slack horizontals.",
    ],
    [
        ("citrus-park-screen-repair.html", "Citrus Park"),
        ("tampa-screen-repair.html", "Tampa"),
        ("carrollwood-screen-repair.html", "Carrollwood"),
        ("oldsmar-screen-repair.html", "Oldsmar"),
        ("clearwater-screen-repair.html", "Clearwater"),
        ("hillsborough-county-screen-repair.html", "Hillsborough hub"),
        ("rescreens.html", "Rescreens"),
        ("gutters-and-screens.html", "Super gutters"),
        ("pool-enclosures.html", "New enclosures"),
        ("storm-screen-repair.html", "Storm repair"),
    ],
    [
        ("Do you serve Town 'n' Country, FL?", "Yes. Town 'n' Country is a regular west Hillsborough route — Chris confirms travel from NPR when you call."),
        ("Is west Hillsborough different from inland Brandon for cages?", "Bay-adjacent lots see more humidity on lower panels; inland sees more UV and thunder wind — Chris scopes accordingly."),
        ("Can you fix hurricane-damaged roof panels only?", "Often, when posts are plumb and remaining mesh is tight. Photos of every torn bay help Chris quote partial vs full."),
        ("Do you install super gutters on older west-side cages?", "Yes, when headers support oversized enclosure gutters — quoted with rescreen work."),
        ("How do I book Town 'n' Country with a Citrus Park address?", "Mention both — Chris batches west Hillsborough loops and confirms the travel window."),
    ],
    [
        ("<strong>Bay-adjacent or inland</strong>", "West-side humidity vs thunder wear differs — say which fits your lot."),
        ("<strong>Photo hurricane-era damage</strong>", "Older patches and roof sag help Chris judge partial vs full scope."),
        ("<strong>Confirm travel from NPR</strong>", "West Hillsborough days are scheduled — not assumed same-week."),
    ],
    "Town 'n' Country screen repair — west Hillsborough owner-direct.",
    [
        (G["cage2"], "Pool cage Town n Country west Hillsborough"),
        (G["door"], "Lanai door repair Town n Country"),
        (G["done"], "Completed rescreen west Hillsborough"),
        (G["mesh"], "Screen mesh replacement Town n Country"),
    ],
    [
        (G["lanai"], "Lanai enclosure Town n Country FL"),
        (G["work"], "Screen repair work west Hillsborough"),
    ],
))

HILLSBOROUGH_CITIES.append(C(
    "riverview-screen-repair", "Riverview", HILL, HILL_L,
    "Screen Repair Riverview FL | Pool Cage Rescreen &amp; Family Cages | Screen Team",
    "Pool cage rescreen, lanai repair &amp; super gutters in Riverview, FL. South county growth, master-planned pools. Chris Westcott. (727) 386-6562.",
    "screen repair Riverview FL, pool cage rescreen Riverview, Boyette screen repair, Apollo Beach screen repair, family pool cage Riverview",
    "Screen Repair, Pool Cages &amp; Super Gutters in Riverview, FL",
    "South Hillsborough growth corridor — master-planned pools, family cages, and pet-worn door panels. Full rescreens, new-enclosure partner inquiries, and super gutters with travel confirmed from NPR.",
    "Riverview — south county growth and family pool cages",
    [
        "Riverview exploded across south Hillsborough in the 2000s and 2010s — Boyette, FishHawk-adjacent streets, and master-planned communities where nearly every backyard has a pool cage before the closing table dries. Those enclosures are hitting their first real rescreen cycle: mesh that looked fine at five years is chalky at twelve, dog doors are shredded, and afternoon thunder peels roof horizontals on wide two-car-garage lots. Homeowners search <strong>screen repair Riverview FL</strong> and need quotes that account for cage size, not ranch-lanai assumptions.",
        "Family pools dominate Riverview calls — kids, pets, and weekend traffic through the cage door wear spline faster than UV alone. Chris Westcott quotes <a href=\"pet-resistant-screen-mesh.html\">pet-resistant mesh</a> on abuse doors when standard fiberglass failed twice in one season. He separates partial <a href=\"pool-cage-repair.html\">pool cage repair</a> from full <a href=\"rescreens.html\">rescreen</a> honestly: one torn roof row after a squall is not always a cage-wide job.",
        "Screen Team routes Riverview from New Port Richey with travel confirmed at booking — often the same south Hillsborough day as <a href=\"brandon-screen-repair.html\">Brandon</a> or <a href=\"valrico-screen-repair.html\">Valrico</a>. Text photos to <a href=\"tel:7273866562\">(727) 386-6562</a> with community name when applicable; master-planned access and cage footprint help Chris ballpark tall and wide enclosures before he crosses the county.",
    ],
    "Riverview neighborhoods &amp; enclosure types",
    [
        ("<strong>Boyette / Boyette Farms</strong>", "2000s cages entering first full rescreen cycle"),
        ("<strong>Providence Lakes / Summerfield</strong>", "family pools, pet-damaged door panels"),
        ("<strong>Alafia corridor / south Riverview</strong>", "wind-exposed roof rows, storm patches"),
        ("<strong>Apollo Beach border</strong>", "bay-influenced humidity on select west pockets"),
        ("<strong>US-301 growth corridors</strong>", "newer subdivisions, wide cage footprints"),
    ],
    "<strong>South county loop:</strong> Riverview pairs with <a href=\"brandon-screen-repair.html\">Brandon</a>, <a href=\"valrico-screen-repair.html\">Valrico</a>, and <a href=\"apollo-beach-screen-repair.html\">Apollo Beach</a> when Chris batches a south Hillsborough day.",
    "Priority work: full rescreens, new enclosure inquiries, super gutters",
    [
        "Full pool cage rescreens are the Riverview call once oxidation is uniform — common on 2005–2015 stock that has never been refreshed. Chris strips failed mesh, checks posts and doors, and installs new screen with tension suited to wide master-planned footprints. Partial quotes remain when only the abuse door or one storm-torn roof row needs attention.",
        "Building on a new Riverview lot or replacing a storm-damaged cage? Screen Team opens <a href=\"pool-enclosures.html\">new enclosure inquiries</a> through licensed partners when Hillsborough permits and engineering apply. Chris reviews your pad photos, explains the partner path, and stays your local owner contact through coordination.",
        "Super gutters matter on Riverview cages where builder-grade troughs clog with oak litter from young trees still maturing along lot lines. Overflow soaks header spline and shortens mesh life. Ask about <a href=\"gutters-and-screens.html\">gutters and screens</a> during the rescreen quote — especially before hurricane season loads debris onto roof panels.",
    ],
    "South Hillsborough growth and storm wear on Riverview cages",
    [
        "Riverview is inland south county — afternoon thunder and UV drive most failures, with select west pockets near Apollo Beach picking up extra humidity. Wind loads wide roof spans on master-planned cages harder than compact ranch enclosures. Chris patches isolated storm tears; cage-wide chalky mesh means a full rescreen is the durable fix.",
        "Pets and kids destroy lower door panels before roof mesh fails — if the latch drifts but walls look fine, the door bay is often the repair. Young neighborhood oaks will increase leaf litter on gutters over the next decade; upgrading headers during a rescreen saves a second trip.",
    ],
    [
        ("brandon-screen-repair.html", "Brandon"),
        ("valrico-screen-repair.html", "Valrico"),
        ("apollo-beach-screen-repair.html", "Apollo Beach"),
        ("gibsonton-screen-repair.html", "Gibsonton"),
        ("sun-city-center-screen-repair.html", "Sun City Center"),
        ("hillsborough-county-screen-repair.html", "Hillsborough hub"),
        ("rescreens.html", "Rescreens"),
        ("pool-enclosures.html", "New enclosures"),
        ("gutters-and-screens.html", "Super gutters"),
        ("pet-resistant-screen-mesh.html", "Pet-resistant mesh"),
    ],
    [
        ("Do you serve Riverview and Boyette?", "Yes. Riverview is a regular south Hillsborough route — travel confirmed from NPR at booking."),
        ("Can you rescreen large master-planned pool cages?", "Yes. Wide footprints are quoted from photos — Chris prices size and access upfront."),
        ("Do you install pet-resistant mesh on cage doors?", "Yes. Abuse doors on family pools often get pet-resistant mesh when fiberglass keeps failing."),
        ("How do I start a new enclosure inquiry in Riverview?", "Call Chris or begin on <a href=\"pool-enclosures.html\">pool enclosures</a> — partner path handles permits when required."),
        ("Should I bundle super gutters with a first rescreen?", "Often smart on 2000s stock with builder-grade gutters — Chris flags overflow risk during the quote walk."),
    ],
    [
        ("<strong>Name the community</strong>", "Boyette, Summerfield, and similar plans help scope cage size."),
        ("<strong>Photo the abuse door</strong>", "Pet and kid wear is common — close-ups speed pet-mesh recommendations."),
        ("<strong>Confirm south county travel</strong>", "Riverview batches from NPR — call early for aligned Hillsborough days."),
    ],
    "Riverview screen repair — south county family cages, owner-direct.",
    [
        (G["rescreen"], "Full pool cage rescreen Riverview"),
        (G["cage3"], "Family pool cage Riverview FL"),
        (G["pano1"], "Pool enclosure panorama south Hillsborough"),
        (G["tall"], "Tall cage rescreen Riverview"),
    ],
    [
        (G["cage2"], "Pool cage repair Riverview"),
        (G["porch"], "Lanai and porch screens Riverview"),
    ],
))

HILLSBOROUGH_CITIES.append(C(
    "valrico-screen-repair", "Valrico", HILL, HILL_L,
    "Screen Repair Valrico FL | Pool Cage Rescreen &amp; Suburban Cages | Screen Team",
    "Pool cage rescreen, lanai repair &amp; super gutters in Valrico, FL. East of Brandon, Lithia border. Chris Westcott. (727) 386-6562.",
    "screen repair Valrico FL, pool cage rescreen Valrico, Lithia screen repair, east Hillsborough pool cage",
    "Screen Repair, Pool Cages &amp; Super Gutters in Valrico, FL",
    "East of Brandon — suburban cages, Lithia-border oaks, and honest east Hillsborough storm wear. Full rescreens, new-enclosure partner path, and super gutters from Chris Westcott.",
    "Valrico — east of Brandon, suburban cages and Lithia border",
    [
        "Valrico sits east of Brandon on the road toward Plant City and Lithia — suburban lots, brick-front homes, and pool cages from the 1990s through 2010s that share Brandon's storm exposure without Brandon's traffic. Oak canopy increases toward the <strong>Lithia</strong> border; open subdivisions near Valrico Road see more wind on roof panels and fewer leaves in the gutter line. Homeowners search <strong>screen repair Valrico FL</strong> when mesh is uniformly chalky or when an east-side thunder cell peeled a roof horizontal overnight.",
        "Chris Westcott treats Valrico as east Hillsborough cage country: inspect posts after storms, quote partial <a href=\"pool-cage-repair.html\">pool cage repair</a> when one bay failed, and recommend full <a href=\"rescreens.html\">rescreen</a> when every wall shows the same brittle gray. Tall cages near Lithia-adjacent streets get height priced from photos — not single-story assumptions. Valrico homeowners often share Brandon storm stories without Brandon traffic — plan travel confirmation when you call from NPR.",
        "Screen Team confirms travel from New Port Richey at booking — Valrico often shares a Hillsborough day with <a href=\"brandon-screen-repair.html\">Brandon</a>, <a href=\"plant-city-screen-repair.html\">Plant City</a>, or <a href=\"riverview-screen-repair.html\">Riverview</a>. Text photos to <a href=\"tel:7273866562\">(727) 386-6562</a> and Chris will outline scope, gutter needs, and whether a new-enclosure conversation belongs on <a href=\"pool-enclosures.html\">pool enclosures</a> instead of a rescreen.",
    ],
    "Valrico neighborhoods &amp; enclosure types",
    [
        ("<strong>Valrico core / Lithia-Pinecrest</strong>", "oak canopy, leaf-clogged cage gutters"),
        ("<strong>Brandon border / Dover area</strong>", "mixed ranch and two-story cages"),
        ("<strong>Buckhorn / Cork area</strong>", "open lots, wind-loaded roof horizontals"),
        ("<strong>Plant City approach corridors</strong>", "older ranch cages, porch screen batches"),
        ("<strong>Bloomingdale adjacency</strong>", "tall family cages on east Hillsborough loops"),
    ],
    "<strong>East Hillsborough:</strong> Valrico routes pair with <a href=\"brandon-screen-repair.html\">Brandon</a> and <a href=\"plant-city-screen-repair.html\">Plant City</a> — mention multiple addresses when scheduling from NPR.",
    "Priority work: full rescreens, new enclosure inquiries, super gutters",
    [
        "Full pool cage rescreens dominate Valrico when oxidation is cage-wide — typical on enclosures that survived a decade of east-side thunder without a gutter upgrade. Chris removes failed mesh, verifies aluminum, and installs new screen with proper tension. Partial work stays available when only a storm-torn roof row or dog door needs replacement.",
        "New pool cage on a Valrico lot or replacing collapsed structure after a named storm? Screen Team routes <a href=\"pool-enclosures.html\">new enclosure inquiries</a> through licensed partners when Hillsborough permits and engineering are required. Chris scopes photos first and stays your owner contact.",
        "Super gutters solve Valrico's oak-litter problem on Lithia-border lots and shallow builder troughs on 2000s subdivisions. Pair <a href=\"gutters-and-screens.html\">gutters and screens</a> with a rescreen before the next season loads debris onto slack roof panels. <a href=\"lanai-screen-replacement.html\">Lanai replacement</a> and window screens ride on the same confirmed travel day.",
    ],
    "East Hillsborough thunder and oak wear on Valrico cages",
    [
        "Valrico is fully inland — afternoon cells build east of Tampa Bay and unload on roof horizontals before weakening. UV chalks south-facing walls; oak litter toward Lithia clogs gutters and rots header spline. Chris patches isolated tears when posts are sound; uniform brittle mesh means rescreen the entire cage.",
        "Wind on open Buckhorn-area lots loads wide roof spans harder than tree-sheltered pockets. After storms, photograph every damaged bay — partial <a href=\"storm-screen-repair.html\">storm repair</a> often restores the enclosure without a full rescreen when aluminum stayed plumb.",
    ],
    [
        ("brandon-screen-repair.html", "Brandon"),
        ("plant-city-screen-repair.html", "Plant City"),
        ("riverview-screen-repair.html", "Riverview"),
        ("lithia-screen-repair.html", "Lithia"),
        ("dover-screen-repair.html", "Dover"),
        ("hillsborough-county-screen-repair.html", "Hillsborough hub"),
        ("rescreens.html", "Rescreens"),
        ("gutters-and-screens.html", "Super gutters"),
        ("pool-enclosures.html", "New enclosures"),
        ("storm-screen-repair.html", "Storm repair"),
    ],
    [
        ("Do you serve Valrico east of Brandon?", "Yes. Valrico is a regular east Hillsborough stop — travel confirmed from NPR when you book."),
        ("Is Valrico different from Brandon for cage wear?", "Similar storm exposure; Valrico picks up more oak litter toward the Lithia border — gutter condition matters."),
        ("Can you quote from photos for Valrico cages?", "Yes. Wide shots plus roof and door close-ups let Chris ballpark partial vs full before travel."),
        ("Do you handle new enclosures in Valrico?", "New builds use the partner path on <a href=\"pool-enclosures.html\">pool enclosures</a> when permits apply."),
        ("Should I upgrade gutters during a Valrico rescreen?", "Often yes under oak canopy — Chris flags shallow troughs during the frame walk."),
    ],
    [
        ("<strong>Note Lithia-border oaks</strong>", "Heavy canopy changes gutter wear — mention tree cover when texting."),
        ("<strong>Photo east-side storm damage</strong>", "Roof rows fail first in thunder cells — include wide and close shots."),
        ("<strong>Batch with Brandon</strong>", "If neighbors need work, say so — Chris groups east Hillsborough routes."),
    ],
    "Valrico screen repair — east Hillsborough suburban cages.",
    [
        (G["side"], "Screen enclosure Valrico east Hillsborough"),
        (G["cage4"], "Pool cage rescreen Valrico FL"),
        (G["pano2"], "Pool enclosure panorama Valrico"),
        (G["door"], "Cage door repair Valrico"),
    ],
    [
        (G["done"], "Completed cage rescreen Valrico"),
        (G["mesh"], "Mesh replacement Valrico Hillsborough"),
    ],
))

HILLSBOROUGH_CITIES.append(C(
    "plant-city-screen-repair", "Plant City", HILL, HILL_L,
    "Screen Repair Plant City FL | Pool Cage Rescreen | Screen Team",
    "Pool cage rescreen, lanai repair &amp; super gutters in Plant City, FL. Strawberry City, east Hillsborough. Travel confirmed from NPR. (727) 386-6562.",
    "screen repair Plant City FL, pool cage rescreen Plant City, east Hillsborough screen repair, lanai repair Plant City",
    "Screen Repair, Pool Cages &amp; Super Gutters in Plant City, FL",
    "Strawberry City at the east edge of Hillsborough — older downtown cages, newer subdivisions west of town, and honest travel scheduling from New Port Richey. Full rescreens, new enclosures, and super gutters.",
    "Plant City — east Hillsborough's Strawberry City cage market",
    [
        "Plant City carries an identity separate from Tampa Bay beach towns — agricultural land, strawberry fields, and a downtown core with older ranch homes whose pool cages date to the 1980s and 1990s. West of downtown, newer subdivisions along the Brandon and Dover corridors brought standard suburban cages that are now entering their first rescreen cycle. Homeowners search <strong>screen repair Plant City FL</strong> when inland thunder has peeled roof panels or when decades of UV turned every wall chalky at once.",
        "Distance matters honestly: Plant City is the far east of Screen Team's regular Hillsborough map. Chris Westcott schedules Plant City with confirmed travel from New Port Richey — often bundled with <a href=\"valrico-screen-repair.html\">Valrico</a>, <a href=\"brandon-screen-repair.html\">Brandon</a>, or <a href=\"dover-screen-repair.html\">Dover</a> so the cross-county day makes sense for everyone. He does not promise same-week slots the way west Pasco jobs receive; he does promise upfront pricing and owner-direct work when the route locks.",
        "Text photos to <a href=\"tel:7273866562\">(727) 386-6562</a> with downtown versus subdivision context. Older downtown cages may need gutter and hardware scrutiny; newer stock west of town often needs tall-cage height confirmed. Chris separates partial <a href=\"pool-cage-repair.html\">pool cage repair</a> from full <a href=\"rescreens.html\">rescreen</a> and opens <a href=\"pool-enclosures.html\">new enclosure inquiries</a> when the pad needs a partner-path build.",
    ],
    "Plant City neighborhoods &amp; enclosure types",
    [
        ("<strong>Downtown / historic core</strong>", "older ranch cages, porch screens, shallow gutters"),
        ("<strong>West Plant City subdivisions</strong>", "2000s cages, first full rescreen cycle"),
        ("<strong>Dover / Pinecrest approach</strong>", "oak litter, east Hillsborough storm wear"),
        ("<strong>Thonotosassa border</strong>", "open lots, wind on roof horizontals"),
        ("<strong>Brandon connector corridors</strong>", "paired routing with east Hillsborough loops"),
    ],
    "<strong>Travel note:</strong> Plant City is farther east — Chris confirms NPR travel when you call. Batching with <a href=\"valrico-screen-repair.html\">Valrico</a> or <a href=\"brandon-screen-repair.html\">Brandon</a> improves scheduling fit.",
    "Priority work: full rescreens, new enclosure inquiries, super gutters",
    [
        "Full pool cage rescreens are the Plant City answer when mesh is brittle cage-wide — common on downtown stock that outlasted its original spline years ago. Chris strips failed screen, inspects aluminum feet and headers, and installs new mesh with tension that survives inland thunder seasons. Partial quotes stay on the table for isolated storm tears on sound frames.",
        "New construction west of Plant City or replacing a collapsed enclosure? Screen Team routes <a href=\"pool-enclosures.html\">new enclosure inquiries</a> through licensed partners when Hillsborough permits and engineering apply. Chris reviews pad photos, explains the partner path, and remains your local contact.",
        "Super gutters matter on older Plant City headers where decades of leaf litter clogged undersized troughs. Pair <a href=\"gutters-and-screens.html\">gutters and screens</a> with a rescreen on downtown cages before another summer loads debris onto slack roof panels. Window screens and porch panels book on the same confirmed east-Hillsborough day.",
    ],
    "Inland east Hillsborough weather on Plant City cages",
    [
        "Plant City sees pure inland Florida wear — hard UV, afternoon thunder, and occasional severe cells that track across the interior before reaching the bay. No salt spray; oxidation and wind drive failures. Chris replaces storm tears when posts are plumb; uniform gray mesh across all bays means a full rescreen is the honest fix.",
        "Oak and pine litter on east-side lots clogs shallow gutters and soaks spline at the header. Downtown ranch cages with original shallow troughs benefit most from super gutter upgrades during a rescreen — one ladder trip instead of two seasons of patched roof rows.",
    ],
    [
        ("valrico-screen-repair.html", "Valrico"),
        ("brandon-screen-repair.html", "Brandon"),
        ("dover-screen-repair.html", "Dover"),
        ("lithia-screen-repair.html", "Lithia"),
        ("tampa-screen-repair.html", "Tampa"),
        ("hillsborough-county-screen-repair.html", "Hillsborough hub"),
        ("rescreens.html", "Rescreens"),
        ("pool-enclosures.html", "New enclosures"),
        ("gutters-and-screens.html", "Super gutters"),
        ("storm-screen-repair.html", "Storm repair"),
    ],
    [
        ("Do you travel to Plant City from New Port Richey?", "Yes — with travel confirmed at booking. Plant City is east Hillsborough; routes often batch with Valrico or Brandon."),
        ("Is Plant City too far for a single panel repair?", "Small jobs meeting the minimum still book when paired with a confirmed east-county route — call to discuss."),
        ("Can you rescreen older downtown Plant City cages?", "Yes. Chris inspects frames on older stock and quotes full or partial work honestly."),
        ("Do you handle new pool enclosures in Plant City?", "New builds use the partner path on <a href=\"pool-enclosures.html\">pool enclosures</a> when permits are required."),
        ("How far ahead should Plant City homeowners schedule?", "Farther east means fewer weekly slots — call early and mention if you can align with a Valrico or Brandon batch."),
    ],
    [
        ("<strong>Downtown vs west subdivisions</strong>", "Older vs 2000s cages scope differently — say which fits your address."),
        ("<strong>Expect confirmed travel</strong>", "Plant City routes from NPR are scheduled — not assumed next-day."),
        ("<strong>Photo the full cage</strong>", "Wide shots help Chris batch east Hillsborough efficiently."),
    ],
    "Plant City screen repair — east Hillsborough, travel confirmed.",
    [
        (G["porch"], "Porch screen repair Plant City FL"),
        (G["cage1"], "Pool cage rescreen Plant City"),
        (G["work"], "Screen enclosure work east Hillsborough"),
        (G["preview"], "Pool enclosure Plant City preview"),
    ],
    [
        (G["pano3"], "Panorama cage rescreen Plant City"),
        (G["rescreen"], "Full rescreen Plant City Hillsborough"),
    ],
))

HILLSBOROUGH_CITIES.append(C(
    "lutz-screen-repair", "Lutz", HILL, HILL_L,
    "Screen Repair Lutz FL | Pool Cage Rescreen &amp; Lake Communities | Screen Team",
    "Pool cage rescreen, lanai repair &amp; super gutters in Lutz, FL. North Hillsborough, Land O Lakes adjacency. Chris Westcott. (727) 386-6562.",
    "screen repair Lutz FL, pool cage rescreen Lutz, Land O Lakes screen repair, north Hillsborough pool cage, lake community screen repair",
    "Screen Repair, Pool Cages &amp; Super Gutters in Lutz, FL",
    "North Hillsborough lake communities — Land O' Lakes adjacency, Pasco border cages, and tall oaks over 1990s pools. Full rescreens, new-enclosure partner path, and super gutters.",
    "Lutz — north Hillsborough lakes and Pasco-border cages",
    [
        "Lutz straddles the line between Tampa sprawl and Pasco calm — lake communities, Chester's Gap-style subdivisions, and pool cages that went up as north Hillsborough filled in during the 1990s and 2000s. <strong>Land O' Lakes</strong> sits just north across the county line; many Lutz homeowners share HOA cage specs and storm exposure with Pasco neighbors even though the zip says Hillsborough. Mature oaks over lake lots drop debris onto roof panels year-round.",
        "Chris Westcott routes Lutz from New Port Richey with travel confirmed — often the same day as <a href=\"carrollwood-screen-repair.html\">Carrollwood</a>, <a href=\"citrus-park-screen-repair.html\">Citrus Park</a>, or Pasco-adjacent work when schedules align. Homeowners search <strong>screen repair Lutz FL</strong> when chalky mesh spans every wall or when a thunder cell peeled the roof row above the lake-facing side.",
        "Text photos to <a href=\"tel:7273866562\">(727) 386-6562</a> with lake-community name when applicable. Chris quotes partial <a href=\"pool-cage-repair.html\">pool cage repair</a> versus full <a href=\"rescreens.html\">rescreen</a> honestly and flags whether <a href=\"gutters-and-screens.html\">super gutters</a> should pair with oak-heavy lots before new mesh goes up. Lutz is north Hillsborough — travel from NPR is confirmed at booking, not assumed same-week like west Pasco.",
    ],
    "Lutz neighborhoods &amp; enclosure types",
    [
        ("<strong>Lake communities / Livingston</strong>", "oak overhang, gutter-clogged headers"),
        ("<strong>Land O' Lakes border</strong>", "2000s cages, paired Pasco-Hillsborough routing"),
        ("<strong>Dale Mabry north / Lutz Lake Fern</strong>", "mixed ranch and two-story enclosures"),
        ("<strong>Cheval / Wesley Chapel adjacency</strong>", "tall cages, wind on open lots"),
        ("<strong>Van Dyke corridor</strong>", "older stock entering rescreen cycle"),
    ],
    "<strong>North county loop:</strong> Lutz pairs with <a href=\"carrollwood-screen-repair.html\">Carrollwood</a>, <a href=\"wesley-chapel-screen-repair.html\">Wesley Chapel</a>, and Pasco-border routes when Chris batches from NPR.",
    "Priority work: full rescreens, new enclosure inquiries, super gutters",
    [
        "Full pool cage rescreens are the Lutz standard once mesh is uniformly oxidized — common on lake-lot cages that caught a decade of oak litter without a gutter upgrade. Chris strips failed screen, checks posts and doors, and installs new mesh with proper tension. Partial quotes when only a storm-torn roof row or pet-damaged door failed. Wide Cheval-adjacent cages and two-story walls get height priced from photos so ladder setup is not a surprise on appointment day.",
        "New pool enclosure on a north Hillsborough pad or replacing storm-damaged structure? Screen Team opens <a href=\"pool-enclosures.html\">new enclosure inquiries</a> through licensed partners when permits and engineering apply. Chris stays your owner contact from photos through partner coordination.",
        "Super gutters matter under Lutz oaks and on lake-community headers where leaves mat in shallow troughs after every front. Pair <a href=\"gutters-and-screens.html\">gutters and screens</a> with a rescreen — especially before hurricane season loads debris onto slack roof horizontals above the water. Window screens, porch panels, and <a href=\"storm-screen-repair.html\">storm patches</a> ride on the same confirmed north-county travel day when you batch with Carrollwood or Pasco-border stops.",
    ],
    "Lake-community oak litter and north Hillsborough storms on Lutz cages",
    [
        "Lutz is inland north county — afternoon thunder and UV dominate. Lake lots add humidity on lower panels without the salt story of beach towns. Oak debris is the silent killer: clogged gutters soak header spline until roof mesh tears in the next gust.",
        "Open lots toward Wesley Chapel see harder wind on tall cage roof rows. Chris patches isolated storm damage when aluminum is plumb; cage-wide chalky mesh means a full rescreen is the durable answer.",
    ],
    [
        ("carrollwood-screen-repair.html", "Carrollwood"),
        ("citrus-park-screen-repair.html", "Citrus Park"),
        ("wesley-chapel-screen-repair.html", "Wesley Chapel"),
        ("land-o-lakes-screen-repair.html", "Land O' Lakes"),
        ("tampa-screen-repair.html", "Tampa"),
        ("hillsborough-county-screen-repair.html", "Hillsborough hub"),
        ("pasco-county-screen-repair.html", "Pasco hub"),
        ("rescreens.html", "Rescreens"),
        ("gutters-and-screens.html", "Super gutters"),
        ("pool-enclosures.html", "New enclosures"),
    ],
    [
        ("Do you serve Lutz and Land O' Lakes border areas?", "Yes. Lutz is regular north Hillsborough work — Chris confirms travel from NPR and may batch Pasco-border stops."),
        ("Why do lake-community cages fail at the gutter?", "Oak litter and humidity clog shallow troughs — super gutters are often the long-term fix."),
        ("Can you rescreen tall cages near Wesley Chapel?", "Yes. Height is priced from photos on north county tall enclosures."),
        ("Do you handle new enclosures in Lutz?", "New builds use the partner path on <a href=\"pool-enclosures.html\">pool enclosures</a> when permits apply."),
        ("How does Lutz scheduling compare to NPR home base?", "Lutz is a confirmed travel day — not same-day west Pasco speed — but routes often align with Carrollwood or Pasco work."),
    ],
    [
        ("<strong>Name the lake community</strong>", "Livingston and similar plans help scope access and cage age."),
        ("<strong>Photo oak-heavy roof rows</strong>", "Canopy debris drives gutter failure — show the header line."),
        ("<strong>Mention Pasco-border stops</strong>", "If you have work in Land O' Lakes too, say so for routing."),
    ],
    "Lutz screen repair — north Hillsborough lake communities.",
    [
        (G["lanai"], "Lanai screen repair Lutz FL"),
        (G["tall"], "Tall pool cage Lutz north Hillsborough"),
        (G["cage2"], "Pool cage rescreen Lutz"),
        (G["pano1"], "Pool enclosure panorama Lutz"),
    ],
    [
        (G["cage3"], "Screen enclosure Lutz lake community"),
        (G["done"], "Completed rescreen Lutz Hillsborough"),
    ],
))

HILLSBOROUGH_CITIES.append(C(
    "citrus-park-screen-repair", "Citrus Park", HILL, HILL_L,
    "Screen Repair Citrus Park FL | Pool Cage &amp; Shopping Corridor | Screen Team",
    "Pool cage rescreen, lanai repair &amp; super gutters in Citrus Park, FL. NW Hillsborough near Carrollwood. Chris Westcott. (727) 386-6562.",
    "screen repair Citrus Park FL, pool cage rescreen Citrus Park, Westchase screen repair, NW Hillsborough screen enclosure",
    "Screen Repair, Pool Cages &amp; Super Gutters in Citrus Park, FL",
    "NW Hillsborough — Citrus Park Mall corridor, Westchase adjacency, and family cages behind 1990s–2000s subdivisions. Full rescreens, new enclosures, and super gutters with NPR travel confirmed.",
    "Citrus Park — NW Hillsborough family cages and corridor lots",
    [
        "Citrus Park is northwest Hillsborough's practical center — the mall corridor, Gunn Highway traffic, and subdivisions like Westchase and Citrus Park proper where pool cages went up in the 1990s and 2000s boom. Families live behind screened pools steps from shopping and school runs; mesh takes abuse from kids, pets, and garage-side basketballs as much as from UV. Homeowners search <strong>screen repair Citrus Park FL</strong> when the abuse door shredded again or when oak litter from Carrollwood-adjacent streets clogged the gutter line.",
        "Chris Westcott batches Citrus Park with <a href=\"carrollwood-screen-repair.html\">Carrollwood</a>, <a href=\"town-n-country-screen-repair.html\">Town 'n' Country</a>, and <a href=\"westchase-screen-repair.html\">Westchase</a> on north-west Hillsborough days from New Port Richey. He quotes partial <a href=\"pool-cage-repair.html\">pool cage repair</a> when one bay failed and full <a href=\"rescreens.html\">rescreen</a> when oxidation is uniform — no upsell when a door panel is the real fix.",
        "Text photos to <a href=\"tel:7273866562\">(727) 386-6562</a> with subdivision name when applicable. Chris will flag super gutter needs under corridor oaks and open the <a href=\"pool-enclosures.html\">new enclosure partner path</a> when your lot needs a permitted build instead of a rescreen on tired aluminum. Citrus Park sits between Carrollwood canopy and Westchase open lots — neighborhood context changes whether gutters or wind damage lead the inspection.",
    ],
    "Citrus Park neighborhoods &amp; enclosure types",
    [
        ("<strong>Citrus Park / Citrus Park Country Club</strong>", "1990s–2000s family cages, pet-worn doors"),
        ("<strong>Westchase border</strong>", "master-planned pools, wide cage footprints"),
        ("<strong>Gunn Highway corridor</strong>", "mixed lanai and pool cage stock"),
        ("<strong>Carrollwood adjacency</strong>", "oak debris on roof panels, gutter clogs"),
        ("<strong>Oldsmar approach streets</strong>", "paired Pinellas-border routing when schedules align"),
    ],
    "<strong>NW Hillsborough:</strong> Citrus Park loops with <a href=\"carrollwood-screen-repair.html\">Carrollwood</a>, <a href=\"town-n-country-screen-repair.html\">Town 'n' Country</a>, and <a href=\"lutz-screen-repair.html\">Lutz</a> on confirmed travel days from NPR.",
    "Priority work: full rescreens, new enclosure inquiries, super gutters",
    [
        "Full pool cage rescreens are the Citrus Park call when every wall is chalky — typical on corridor subdivisions entering their second mesh cycle. Chris strips failed screen, verifies posts and doors, and installs new mesh with tension that survives family traffic and oak-litter seasons. Partial quotes for isolated roof storm tears or single abuse doors.",
        "Building a new cage on a cleared NW Hillsborough lot? Screen Team routes <a href=\"pool-enclosures.html\">new enclosure inquiries</a> through licensed partners when Hillsborough permits and engineering apply. Chris scopes photos and stays your owner contact.",
        "Super gutters matter where shopping-corridor oaks and shallow builder troughs overflow every summer squall. Pair <a href=\"gutters-and-screens.html\">gutters and screens</a> with a rescreen on cages that have been patched at the header twice already. <a href=\"pet-resistant-screen-mesh.html\">Pet-resistant mesh</a> on abuse doors often outlasts repeated fiberglass replacements.",
    ],
    "NW Hillsborough oak litter and family wear on Citrus Park cages",
    [
        "Citrus Park is inland NW county — thunder and UV drive most failures, with Carrollwood-adjacent oaks adding leaf litter that clogs gutters faster than open Westchase lots. Kids and pets destroy door panels before roof mesh fails — Chris recommends pet-resistant upgrades when fiberglass keeps tearing.",
        "Wind on wide Westchase-border cages loads roof horizontals harder than compact ranch lanais near the mall corridor. After storms, photograph torn bays — partial <a href=\"storm-screen-repair.html\">storm repair</a> restores sound aluminum without a full rescreen when oxidation has not spread cage-wide.",
    ],
    [
        ("carrollwood-screen-repair.html", "Carrollwood"),
        ("town-n-country-screen-repair.html", "Town 'n' Country"),
        ("lutz-screen-repair.html", "Lutz"),
        ("tampa-screen-repair.html", "Tampa"),
        ("oldsmar-screen-repair.html", "Oldsmar"),
        ("westchase-screen-repair.html", "Westchase"),
        ("hillsborough-county-screen-repair.html", "Hillsborough hub"),
        ("rescreens.html", "Rescreens"),
        ("gutters-and-screens.html", "Super gutters"),
        ("pool-enclosures.html", "New enclosures"),
    ],
    [
        ("Do you serve Citrus Park and Westchase?", "Yes. NW Hillsborough is a regular route — Chris confirms travel from NPR at booking."),
        ("Can you fix pet-damaged cage doors in Citrus Park?", "Yes. Abuse doors often get pet-resistant mesh when standard fiberglass keeps failing."),
        ("Do Citrus Park cages need super gutters?", "Often under oak canopy — Chris flags shallow troughs during the quote walk."),
        ("How do I start a new enclosure inquiry?", "Begin on <a href=\"pool-enclosures.html\">pool enclosures</a> or call Chris — partner path handles permits when required."),
        ("Can Citrus Park batch with Carrollwood on one trip?", "Yes — mention both addresses when scheduling north-west Hillsborough work."),
    ],
    [
        ("<strong>Name Westchase vs Citrus Park proper</strong>", "Subdivision context helps scope cage size and access."),
        ("<strong>Photo the abuse door</strong>", "Family wear is the top call — close-ups speed the quote."),
        ("<strong>Confirm NW travel day</strong>", "Hillsborough routes from NPR are scheduled — call early in the week."),
    ],
    "Citrus Park screen repair — NW Hillsborough owner-direct.",
    [
        (G["cage4"], "Pool cage Citrus Park NW Hillsborough"),
        (G["mesh"], "Screen mesh replacement Citrus Park"),
        (G["side"], "Enclosure side panels Citrus Park"),
        (G["door"], "Pool cage door Citrus Park FL"),
    ],
    [
        (G["pano2"], "Panorama pool cage Citrus Park"),
        (G["rescreen"], "Full rescreen Citrus Park Hillsborough"),
    ],
))

HILLSBOROUGH_CITIES.append(C(
    "temple-terrace-screen-repair", "Temple Terrace", HILL, HILL_L,
    "Screen Repair Temple Terrace FL | Pool Cage &amp; Tree City | Screen Team",
    "Pool cage rescreen, lanai repair &amp; super gutters in Temple Terrace, FL. Tree City, USF area, mature canopy. Chris Westcott. (727) 386-6562.",
    "screen repair Temple Terrace FL, pool cage rescreen Temple Terrace, USF screen repair, Tree City screen enclosure",
    "Screen Repair, Pool Cages &amp; Super Gutters in Temple Terrace, FL",
    "Florida's Tree City — mature canopy debris through screens, USF-area rentals, and hillside lots near the river. Full rescreens, new-enclosure partner path, and super gutters from Chris Westcott.",
    "Temple Terrace — Tree City canopy and USF-area cages",
    [
        "Temple Terrace wears its Tree City nickname literally — mature oaks and sabal palms arch over streets between the Hillsborough River and the <strong>USF</strong> corridor, dropping leaves, fronds, and limbs onto pool cages year-round. Housing mixes 1960s river-hillside homes with mid-century ranch pools and infill near Busch Boulevard where students and families share the same enclosure headaches: gutter lines clogged after one storm, roof panels punched by debris, spline rotted at the header before mesh looks bad from the pool deck.",
        "Chris Westcott knows canopy cages fail differently than open-lot Brandon stock — you inspect gutters and roof rows first, then walls. Homeowners search <strong>screen repair Temple Terrace FL</strong> when oak litter accelerated oxidation along the top plate or when a frond speared a roof horizontal overnight. Partial <a href=\"pool-cage-repair.html\">pool cage repair</a> when one bay tore; full <a href=\"rescreens.html\">rescreen</a> when every panel shares the same brittle gray.",
        "Screen Team routes Temple Terrace from New Port Richey with travel confirmed — often paired with <a href=\"tampa-screen-repair.html\">Tampa</a> east-side or <a href=\"brandon-screen-repair.html\">Brandon</a> when Hillsborough days align. Text photos to <a href=\"tel:7273866562\">(727) 386-6562</a> and show the header gutter line if leaves sit in the trough — Chris will tell you whether <a href=\"gutters-and-screens.html\">super gutters</a> should bundle with the rescreen.",
    ],
    "Temple Terrace neighborhoods &amp; enclosure types",
    [
        ("<strong>River hills / scenic corridor</strong>", "slope access, debris slides on roof panels"),
        ("<strong>USF / Busch Boulevard area</strong>", "rental turnovers, lanai and porch screen batches"),
        ("<strong>Tree-lined interior streets</strong>", "canopy punctures, gutter-clogged headers"),
        ("<strong>56th Street corridor</strong>", "mixed ranch cages and compact lanais"),
        ("<strong>Brandon border pockets</strong>", "paired east Hillsborough routing"),
    ],
    "<strong>Tree City insight:</strong> Canopy debris drives Temple Terrace failures more than salt or bay humidity — photograph gutter overflow and roof damage when texting quotes.",
    "Priority work: full rescreens, new enclosure inquiries, super gutters",
    [
        "Full pool cage rescreens are the Temple Terrace answer when mesh is chalky cage-wide — often after years of canopy debris shortened spline life at the header. Chris strips failed screen, checks posts on hillside lots, and installs new mesh with proper tension. Partial quotes when a single frond-punched roof row or rental-turnover door is the isolated fix.",
        "New pool enclosure near the river hills or replacing storm-collapsed structure? Screen Team opens <a href=\"pool-enclosures.html\">new enclosure inquiries</a> through licensed partners when Hillsborough permits and engineering apply. Chris stays your owner contact from first photos through partner coordination.",
        "Super gutters are disproportionately valuable in Temple Terrace — undersized troughs under heavy canopy overflow every squall and soak spline at the top plate. Pair <a href=\"gutters-and-screens.html\">gutters and screens</a> with a rescreen before the next limb season. <a href=\"lanai-screen-replacement.html\">Lanai replacement</a> and porch screens book on the same confirmed travel day.",
    ],
    "Tree City canopy debris and inland storms on Temple Terrace cages",
    [
        "Temple Terrace is inland east Tampa — thunder and UV plus relentless canopy litter. Fronds and oak limbs punch roof panels; clogged gutters accelerate header spline failure faster than open-subdivision cages in Riverview. Chris replaces isolated punctures when aluminum is sound; uniform oxidation means rescreen the whole cage.",
        "Hillside lots near the river add access complexity — Chris confirms ladder approach when quoting. USF-area rentals often need door and porch work without full cage scope; he quotes accordingly instead of defaulting to a complete rescreen.",
    ],
    [
        ("tampa-screen-repair.html", "Tampa"),
        ("brandon-screen-repair.html", "Brandon"),
        ("riverview-screen-repair.html", "Riverview"),
        ("seffner-screen-repair.html", "Seffner"),
        ("mango-screen-repair.html", "Mango"),
        ("hillsborough-county-screen-repair.html", "Hillsborough hub"),
        ("rescreens.html", "Rescreens"),
        ("gutters-and-screens.html", "Super gutters"),
        ("pool-enclosures.html", "New enclosures"),
        ("storm-screen-repair.html", "Storm repair"),
    ],
    [
        ("Do you serve Temple Terrace and the USF area?", "Yes. Temple Terrace is a regular east Hillsborough route — travel confirmed from NPR at booking."),
        ("Why do Tree City cages fail at the roof first?", "Canopy debris clogs gutters and punches horizontals — header condition matters as much as mesh age."),
        ("Can you repair rental lanai screens near USF?", "Yes. Partial lanai and porch work quotes separately from full cage rescreens."),
        ("Are super gutters essential under Temple Terrace oaks?", "Often yes — Chris flags shallow troughs during the frame walk on canopy-heavy lots."),
        ("Do you handle new enclosures in Temple Terrace?", "New builds use the partner path on <a href=\"pool-enclosures.html\">pool enclosures</a> when permits apply."),
    ],
    [
        ("<strong>Photo gutter overflow</strong>", "Canopy litter is the main driver — show the header trough if clogged."),
        ("<strong>Note hillside access</strong>", "River-hills lots may need ladder approach confirmed before booking."),
        ("<strong>Separate rental vs owner scope</strong>", "USF-area turnovers often need doors only — say which applies."),
    ],
    "Temple Terrace screen repair — Tree City canopy-smart rescreens.",
    [
        (G["work"], "Screen repair Temple Terrace Tree City"),
        (G["cage1"], "Pool cage rescreen Temple Terrace"),
        (G["porch"], "Porch screen USF area Temple Terrace"),
        (G["pano3"], "Pool enclosure panorama Temple Terrace"),
    ],
    [
        (G["tall"], "Tall cage Temple Terrace Hillsborough"),
        (G["lanai"], "Lanai enclosure Temple Terrace FL"),
    ],
))
