"""County hub page content for Screen Team geo SEO expansion."""
from geo_content import C, G, PASCO, PIN, HILL, PASCO_L, PIN_L, HILL_L

COUNTY_PAGES = [
    C(
        "pinellas-county-screen-repair",
        "Pinellas County",
        PIN,
        PIN_L,
        "Screen Repair Pinellas County FL | Pool Cage Rescreen & Super Gutters | Screen Team",
        "Pinellas County screen repair — full pool cage rescreens, new enclosure partner path, super gutters &amp; lanai work. Chris Westcott. (727) 386-6562.",
        "screen repair Pinellas County, pool cage rescreen Pinellas, super gutters Pinellas County, lanai screen repair Clearwater St Pete",
        "Screen Repair, Pool Cage Rescreens &amp; Super Gutters in Pinellas County, FL",
        "Coastal salt, inland Countryside cages, and barrier-island wind — Pinellas pool enclosures need owner-direct rescreens, super gutters, and honest new-enclosure routing from Chris Westcott.",
        "Pinellas County — coastal enclosures from Clearwater to the beaches",
        [
            "Pinellas County is Tampa Bay's most screen-intensive peninsula: Gulf breezes on <a href=\"clearwater-screen-repair.html\">Clearwater</a> and <a href=\"madeira-beach-screen-repair.html\">Madeira Beach</a> cages, two-story Countryside footprints in <a href=\"largo-screen-repair.html\">Largo</a>, oak-canopy gutters in <a href=\"safety-harbor-screen-repair.html\">Safety Harbor</a>, and retirement-lanai refreshes through <a href=\"seminole-screen-repair.html\">Seminole</a> and <a href=\"pinellas-park-screen-repair.html\">Pinellas Park</a>. When homeowners search <strong>screen repair Pinellas County</strong>, they are usually past the patch stage — chalky mesh cage-wide, a storm row peeled back on the roof, or water sheeting off a shallow gutter onto the header spline.",
            "The Screen Team LLC serves all of Pinellas from New Port Richey with Chris Westcott on every ladder. That matters on a peninsula where subcontractor crews rotate and nobody owns the follow-up call. Chris quotes <a href=\"rescreens.html\">full pool cage rescreens</a> from photos when possible, replaces partial storm bays when aluminum is still plumb, and opens the <a href=\"pool-enclosures.html\">new enclosure partner path</a> when you need permits, engineering, or a ground-up cage on a vacant pad.",
            "Pinellas routes batch north Pinellas (<a href=\"palm-harbor-screen-repair.html\">Palm Harbor</a>, <a href=\"dunedin-screen-repair.html\">Dunedin</a>, <a href=\"tarpon-springs-screen-repair.html\">Tarpon Springs</a>, <a href=\"oldsmar-screen-repair.html\">Oldsmar</a>) with central-corridor stops (<a href=\"st-petersburg-screen-repair.html\">St. Petersburg</a>, <a href=\"gulfport-screen-repair.html\">Gulfport</a>, <a href=\"kenneth-city-screen-repair.html\">Kenneth City</a>) and east-Pinellas pockets (<a href=\"east-lake-screen-repair.html\">East Lake</a>, <a href=\"feather-sound-screen-repair.html\">Feather Sound</a>). Barrier islands like <a href=\"treasure-island-screen-repair.html\">Treasure Island</a> and <a href=\"belleair-screen-repair.html\">Belleair</a> may need access confirmation — Chris handles that in the first text thread, not after he is on the bridge.",
            "Coastal Pinellas cages fail differently than inland ones. Salt accelerates oxidation on lower horizontals and hinge hardware while roof panels still look acceptable from the driveway. Inland subdivisions fail from UV and afternoon squall lines that unzip roof rows first. Chris reads the cage before recommending scope — a lower-panel refresh on a sound frame beats a full rescreen upsell, and a full rescreen beats endless patch squares when every bay is brittle.",
            "Priority revenue work in Pinellas mirrors what the county actually needs: enclosure-wide mesh replacement, oversized <a href=\"gutters-and-screens.html\">super gutters</a> where oak litter and Gulf rain overwhelm shallow troughs, and new-build inquiries routed through licensed partners when structural permits apply. Window screens, lanai doors, and <a href=\"storm-screen-repair.html\">storm patches</a> still book — but the lasting fix on a 1990s Pinellas cage is usually mesh, spline, and drainage done together.",
            "Call or text <a href=\"tel:7273866562\">(727) 386-6562</a> with your city, wide cage photos, and whether you are beach-adjacent or inland. Chris will tell you if you need a panel job, a full rescreen, super gutter work, or a conversation about a brand-new enclosure entirely.",
        ],
        "Cities we serve in Pinellas County",
        [
            ('<a href="clearwater-screen-repair.html"><strong>Clearwater</strong></a>', "beach salt, Countryside two-story cages"),
            ('<a href="st-petersburg-screen-repair.html"><strong>St. Petersburg</strong></a>', "historic porches, mid-century lanais, waterfront cages"),
            ('<a href="largo-screen-repair.html"><strong>Largo</strong></a>', "large inland enclosures, oxidation rescreens"),
            ('<a href="palm-harbor-screen-repair.html"><strong>Palm Harbor</strong></a>', "tall cages, oak-canopy gutters, East Lake border"),
            ('<a href="safety-harbor-screen-repair.html"><strong>Safety Harbor</strong></a>', "bay breezes, retirement lanai refreshes"),
            ('<a href="dunedin-screen-repair.html"><strong>Dunedin</strong></a>', "downtown porches, Honeymoon Island adjacency"),
            ('<a href="oldsmar-screen-repair.html"><strong>Oldsmar</strong></a>', "Tampa Road corridors, mixed-age cages"),
            ('<a href="tarpon-springs-screen-repair.html"><strong>Tarpon Springs</strong></a>', "north Pinellas salt, sponge-dock adjacency"),
            ('<a href="seminole-screen-repair.html"><strong>Seminole</strong></a>', "mid-county pools, door spline traffic"),
            ('<a href="pinellas-park-screen-repair.html"><strong>Pinellas Park</strong></a>', "ranch cages, US-19 corridor access"),
            ('<a href="gulfport-screen-repair.html"><strong>Gulfport</strong></a>', "waterfront wear, arts-district porches"),
            ('<a href="belleair-screen-repair.html"><strong>Belleair</strong></a>', "estate lanais, Belleair Bluffs border"),
            ('<a href="kenneth-city-screen-repair.html"><strong>Kenneth City</strong></a>', "compact pools, porch screen batches"),
            ('<a href="madeira-beach-screen-repair.html"><strong>Madeira Beach</strong></a>', "barrier-island wind, salt lower rows"),
            ('<a href="treasure-island-screen-repair.html"><strong>Treasure Island</strong></a>', "Gulf exposure, vacation-rental refreshes"),
            ('<a href="east-lake-screen-repair.html"><strong>East Lake</strong></a>', "two-story cages, ladder-height quotes"),
            ('<a href="feather-sound-screen-repair.html"><strong>Feather Sound</strong></a>', "executive homes, tall enclosure gutters"),
        ],
        "<strong>Peninsula routing:</strong> Pinellas jobs batch by geography — mention if you have a second address in <a href=\"pasco-county-screen-repair.html\">Pasco</a> or need cross-bay <a href=\"hillsborough-county-screen-repair.html\">Hillsborough</a> coordination.",
        "Priority work: full rescreens, new enclosure inquiries, super gutters",
        [
            "Full <a href=\"rescreens.html\">pool cage rescreens</a> are the core Pinellas call once mesh turns chalky on every wall — common on cages built during the 1980s–2000s boom from Clearwater east through Largo and Seminole. Chris strips oxidized screen, checks posts, doors, and kick plates, then rolls new mesh with proper spline tension. Most single-story residential cages finish in a day; two-story Countryside and East Lake footprints may span two days when ladder setup and bay count demand it.",
            "Need a <em>new</em> pool enclosure or structural rebuild after a collapse? Screen Team routes those inquiries through licensed contractor partners when engineering stamps or county permits are required. Chris remains your local contact — you are not handed off to a call center. Start on <a href=\"pool-enclosures.html\">pool enclosures</a> and bring pad dimensions or engineer drawings if you already have them.",
            "Super gutters and oversized enclosure gutters solve the Pinellas problem of oak canopy and Gulf squalls dumping water into shallow troughs that were never sized for a full cage roof. Overflow stains fascia, rots spline along the top plate, and makes homeowners think the mesh failed when drainage is the real culprit. Ask about <a href=\"gutters-and-screens.html\">gutters and screens</a> during the same visit as a rescreen so you are not paying setup twice.",
            "Partial work still matters: storm-torn roof horizontals after summer squalls, dog-damaged lanai doors in Seminole and Pinellas Park, and salt-chewed lower panels on Madeira Beach and Treasure Island waterfront lots. Chris quotes honestly — if only the door leaf failed, you get a door quote; if the whole cage is oxidized, he says so before booking.",
        ],
        "Coastal salt, squall wind, and inland UV on Pinellas cages",
        [
            "Afternoon storms track east across the peninsula and peel roof horizontals before walls show stress. Chris replaces torn sections with proper tension when aluminum is still plumb — see <a href=\"storm-screen-repair.html\">storm screen repair</a>. When oxidation is uniform and mesh snaps in your fingers, a full rescreen is the honest fix — mixing bright new squares on one wall with gray brittle neighbors fails within a season.",
            "Coastal properties from Clearwater Beach through Gulfport and the barrier islands see salt on lower panels and hinge corrosion years before inland cages. Chris may quote lower-bay replacement alone when upper mesh still holds tension. Inland Countryside and Feather Sound cages skew tall — height and ladder access are priced upfront, not discovered mid-job.",
            "Pet-resistant mesh upgrades on high-traffic doors are common in family pools across Largo and Palm Harbor. Fine <a href=\"pet-resistant-screen-mesh.html\">pet-resistant mesh</a> on the abuse door while standard fiberglass stays on upper bays balances durability with airflow. No-see-um upgrades show up on evening-use lanais in Dunedin and Safety Harbor where gnats ruin dinner on the patio.",
        ],
        [
            ("clearwater-screen-repair.html", "Clearwater"),
            ("st-petersburg-screen-repair.html", "St. Petersburg"),
            ("largo-screen-repair.html", "Largo"),
            ("palm-harbor-screen-repair.html", "Palm Harbor"),
            ("dunedin-screen-repair.html", "Dunedin"),
            ("safety-harbor-screen-repair.html", "Safety Harbor"),
            ("pasco-county-screen-repair.html", "Pasco hub"),
            ("rescreens.html", "Full rescreens"),
            ("gutters-and-screens.html", "Super gutters"),
            ("pool-enclosures.html", "New enclosures"),
            ("storm-screen-repair.html", "Storm repair"),
            ("service-areas.html", "All areas"),
        ],
        [
            ("Does Screen Team serve all of Pinellas County?", "Yes — from Clearwater and St. Pete through Palm Harbor, Dunedin, Seminole, and barrier islands. Call to confirm island access or HOA gate details."),
            ("How much does a pool cage rescreen cost in Pinellas?", "Full rescreens often start near $1,995 with most Pinellas cages landing $2,500–$6,500+ depending on size, height, mesh type, and access. Chris ballparks from photos when possible."),
            ("Can you repair just a few torn panels after a storm?", "Yes. Pinellas afternoon storms often tear roof horizontals first. Chris replaces only failed panels when the frame is sound and surrounding mesh still has life."),
            ("Do you install super gutters on Pinellas pool cages?", "Yes. Oversized enclosure gutters and gutter/screen bundles are quoted with cage work — especially under oak canopy in Safety Harbor and Palm Harbor."),
            ("Can you help if I need a brand-new pool enclosure?", "New enclosure inquiries go through a licensed partner path when permits and engineering are required. Chris stays your local contact — start on pool enclosures."),
        ],
        [
            ("<strong>Beach vs inland</strong>", "Salt wear and wind loads differ — note your city and proximity to the Gulf."),
            ("<strong>Photo roof + lower row</strong>", "Wide cage shot plus close-ups of tears or chalky mesh."),
            ("<strong>Bundle gutters</strong>", "If headers stay wet after rain, ask about super gutters during the rescreen quote."),
        ],
        "Pinellas County screen repair — coastal cages, owner on every job.",
        [
            (G["pano1"], "Pool cage rescreen Pinellas County coastal"),
            (G["cage2"], "Lanai screen repair Clearwater Pinellas"),
            (G["tall"], "Two-story enclosure rescreen Pinellas"),
            (G["door"], "Pool cage door spline Pinellas County"),
        ],
        [
            (G["cage3"], "Pool enclosure — Pinellas County"),
            (G["done"], "Completed cage rescreen — Pinellas peninsula"),
        ],
        area_type="AdministrativeArea",
    ),
    C(
        "pasco-county-screen-repair",
        "Pasco County",
        PASCO,
        PASCO_L,
        "Screen Repair Pasco County FL | Pool Cage Rescreen & Super Gutters | Screen Team",
        "Pasco County screen repair from our New Port Richey home base — full rescreens, new enclosure partner path, super gutters &amp; lanai work. Chris Westcott. (727) 386-6562.",
        "screen repair Pasco County, pool cage rescreen Pasco, super gutters Pasco County, lanai screen repair New Port Richey Wesley Chapel",
        "Screen Repair, Pool Cage Rescreens &amp; Super Gutters in Pasco County, FL",
        "Home-base county for The Screen Team LLC — west Pasco canal cages, NPR scheduling speed, and east Pasco growth enclosures from Wesley Chapel to Dade City.",
        "Pasco County — Screen Team home base and fastest routes",
        [
            "Pasco County is where The Screen Team LLC lives. <a href=\"new-port-richey-screen-repair.html\">New Port Richey</a> is home base — Chris Westcott already knows how west Pasco cages age along the Pithlachascotee, on US-19 canal streets, and in ranch subdivisions east of Little Road. When homeowners search <strong>screen repair Pasco County</strong>, they are often calling from minutes away, not across a bridge.",
            "That home-base advantage shows up in scheduling. Same-week slots are more common in <a href=\"port-richey-screen-repair.html\">Port Richey</a>, <a href=\"holiday-screen-repair.html\">Holiday</a>, and <a href=\"hudson-screen-repair.html\">Hudson</a> than on cross-bay Pinellas or Hillsborough days. East Pasco growth corridors — <a href=\"wesley-chapel-screen-repair.html\">Wesley Chapel</a>, <a href=\"land-o-lakes-screen-repair.html\">Land O' Lakes</a>, <a href=\"trinity-screen-repair.html\">Trinity</a>, and <a href=\"odessa-screen-repair.html\">Odessa</a> — add newer two-story cages, shallow gutters under fresh oak plantings, and HOAs that want clean sight lines after a rescreen.",
            "Pasco housing spans decades: 1970s canal lanais in NPR and Port Richey, 1990s pool cages in Holiday and Hudson, and 2010s enclosures in Wesley Chapel and Trinity with taller walls and bigger roof footprints. Chris inspects aluminum feet for corrosion on waterfront lots, checks whether oak litter is clogging undersized gutters, and quotes <a href=\"rescreens.html\">full pool cage rescreens</a> when oxidation is uniform — not a patch job that fails next summer.",
            "Priority work in Pasco is the same work Chris does every week at home: enclosure-wide mesh replacement, <a href=\"gutters-and-screens.html\">super gutters</a> where drainage was never sized for the cage roof, and <a href=\"pool-enclosures.html\">new enclosure inquiries</a> through licensed partners when you need permits on a vacant pad or a structural rebuild. Inland east Pasco — <a href=\"zephyrhills-screen-repair.html\">Zephyrhills</a> and <a href=\"dade-city-screen-repair.html\">Dade City</a> — gets honest travel timing when routes batch with Wesley Chapel or Land O' Lakes stops.",
            "West Pasco pairs naturally on one trip: NPR, Port Richey, Holiday, and Hudson often share a morning loop. Mention a second Pasco address when you call — Chris batches neighbor cities without treating every stop like a new trip fee surprise. Small jobs — window screens, single panels, porch patches — still meet the $150 minimum and ride along with rescreen days.",
            "Text photos to <a href=\"tel:7273866562\">(727) 386-6562</a> with your Pasco city and whether you are canal-side or inland. Chris will tell you whether you need a panel job, a full rescreen, super gutter work, or a new-enclosure conversation before he loads the ladder.",
        ],
        "Cities we serve in Pasco County",
        [
            ('<a href="new-port-richey-screen-repair.html"><strong>New Port Richey</strong></a>', "home base, canal cages, fastest scheduling"),
            ('<a href="port-richey-screen-repair.html"><strong>Port Richey</strong></a>', "Gulf-side salt, waterfront lower panels"),
            ('<a href="holiday-screen-repair.html"><strong>Holiday</strong></a>', "Anclote adjacency, ranch pool cages"),
            ('<a href="hudson-screen-repair.html"><strong>Hudson</strong></a>', "coastal wear, retirement lanai refreshes"),
            ('<a href="land-o-lakes-screen-repair.html"><strong>Land O\' Lakes</strong></a>', "east Pasco growth, two-story cages"),
            ('<a href="wesley-chapel-screen-repair.html"><strong>Wesley Chapel</strong></a>', "newer subdivisions, tall enclosures"),
            ('<a href="trinity-screen-repair.html"><strong>Trinity</strong></a>', "executive homes, oak-canopy gutters"),
            ('<a href="odessa-screen-repair.html"><strong>Odessa</strong></a>', "rural lots, large cage footprints"),
            ('<a href="zephyrhills-screen-repair.html"><strong>Zephyrhills</strong></a>', "inland UV, older ranch enclosures"),
            ('<a href="dade-city-screen-repair.html"><strong>Dade City</strong></a>', "east Pasco historic homes, porch screens"),
        ],
        "<strong>Home-base county:</strong> West Pasco routes from NPR often book same-week. East Pasco (<a href=\"wesley-chapel-screen-repair.html\">Wesley Chapel</a>, <a href=\"land-o-lakes-screen-repair.html\">Land O' Lakes</a>) batches with <a href=\"pinellas-county-screen-repair.html\">Pinellas</a> border stops when possible.",
        "Priority work: full rescreens, new enclosure inquiries, super gutters",
        [
            "Full <a href=\"rescreens.html\">pool cage rescreens</a> are the bread-and-butter Pasco job — chalky mesh on every wall from decades of Gulf humidity and UV. Chris removes failed screen, verifies posts and doors are square, and installs new mesh with spline tension that survives the next storm season. Typical west Pasco footprints finish in a day; taller Wesley Chapel and Trinity cages may need a second day when bay count and ladder setup demand it.",
            "Shopping for a brand-new pool cage or replacing a collapsed structure? Chris opens a <a href=\"pool-enclosures.html\">new enclosure inquiry</a> and connects you to the licensed partner path for permits and engineering while staying your local point of contact. You are not passed to a national call center — the same owner who rescreens your lanai scopes the new-build conversation.",
            "Super gutters along the cage header fix the Pasco pattern of oak litter clogging shallow troughs installed when cages were smaller. Water sheets onto the top spline row, accelerates oxidation, and makes homeowners blame mesh when drainage is the root cause. Pair <a href=\"gutters-and-screens.html\">gutters and screens</a> in one quote when headers stay wet after every squall.",
            "Partial repairs stay honest: storm-torn roof rows after afternoon cells, dog-damaged doors in NPR and Holiday, and salt-chewed lower panels on Port Richey canal lots. Chris quotes the scope that matches the cage — door-only when the walls are sound, full rescreen when every bay is brittle.",
        ],
        "West Pasco canals vs east Pasco growth cages",
        [
            "Canal homes in NPR, Port Richey, and Hudson show salt corrosion and chalky bottom rows before roof panels fail. Chris checks hinge hardware and kick plates on waterfront approaches. Inland Wesley Chapel and Land O' Lakes cages fail more from UV and wind on tall roof horizontals — ladder height is priced upfront.",
            "After tropical weather, photograph every torn bay before calling. Partial <a href=\"storm-screen-repair.html\">storm repairs</a> restore the cage when posts are still plumb. Uniform oxidation that cracks in your fingers means a full rescreen is the lasting fix — not a third patch square.",
            "Pet-resistant mesh on abuse doors is common in family pools across Trinity and Odessa. East Pasco afternoon storms track similarly to west Pasco — roof horizontals unzip first. Chris replaces with proper tension so the next cell does not cascade tears down the slope.",
        ],
        [
            ("new-port-richey-screen-repair.html", "New Port Richey"),
            ("wesley-chapel-screen-repair.html", "Wesley Chapel"),
            ("holiday-screen-repair.html", "Holiday"),
            ("hudson-screen-repair.html", "Hudson"),
            ("land-o-lakes-screen-repair.html", "Land O' Lakes"),
            ("trinity-screen-repair.html", "Trinity"),
            ("pinellas-county-screen-repair.html", "Pinellas hub"),
            ("rescreens.html", "Full rescreens"),
            ("gutters-and-screens.html", "Super gutters"),
            ("pool-enclosures.html", "New enclosures"),
            ("pool-cage-repair.html", "Cage repair"),
            ("service-areas.html", "All areas"),
        ],
        [
            ("Is there a trip fee in Pasco County?", "West Pasco around New Port Richey is home base — standard work is quoted without surprise trip fees. East Pasco travel is included upfront in the quote when it applies."),
            ("How fast can you schedule in Pasco?", "Many west Pasco repairs book within a few days; NPR and Port Richey often land same-week when materials are in stock."),
            ("Do you do full pool cage rescreens in Pasco?", "Yes — full and partial rescreens are core work. Chris quotes from photos when possible."),
            ("Can you help if I need a brand-new enclosure?", "New enclosure inquiries use the licensed partner path when permits and engineering are required. Call Chris to start."),
            ("Do you install super gutters on Pasco pool cages?", "Yes. Oversized enclosure gutters are quoted with cage work — especially under oak canopy in Trinity and Land O' Lakes."),
        ],
        [
            ("<strong>Mention canal vs inland</strong>", "Salt wear and access differ on waterfront NPR and Port Richey lots."),
            ("<strong>Text photos first</strong>", "Wide cage shot plus close-ups of tears or chalky mesh."),
            ("<strong>Bundle east Pasco stops</strong>", "Second Pasco address? Say so — Chris batches neighbor cities."),
        ],
        "Pasco County screen repair — call the owner at home base.",
        [
            (G["pano2"], "Pool cage rescreen Pasco County home base"),
            (G["cage1"], "Lanai screen repair west Pasco"),
            (G["cage4"], "Pool enclosure panels Pasco"),
            (G["door"], "Pool cage door repair New Port Richey"),
        ],
        [
            (G["side"], "Screen enclosure — west Pasco"),
            (G["done"], "Completed cage rescreen — Pasco County"),
        ],
        area_type="AdministrativeArea",
    ),
    C(
        "hillsborough-county-screen-repair",
        "Hillsborough County",
        HILL,
        HILL_L,
        "Screen Repair Hillsborough County FL | Pool Cage Rescreen & Super Gutters | Screen Team",
        "Hillsborough County screen repair — Tampa, Brandon, Carrollwood &amp; east-county cages. Full rescreens, new enclosure partner path &amp; super gutters. Chris Westcott. (727) 386-6562.",
        "screen repair Hillsborough County, pool cage rescreen Tampa, super gutters Hillsborough, lanai screen repair Brandon Riverview",
        "Screen Repair, Pool Cage Rescreens &amp; Super Gutters in Hillsborough County, FL",
        "Cross-bay from New Port Richey — Hillsborough pool cages in Tampa, Brandon, and Carrollwood get owner-direct rescreens, super gutters, and new-enclosure routing without a subcontractor lottery.",
        "Hillsborough County — cross-bay Tampa routes from NPR home base",
        [
            "Hillsborough County is the cross-bay half of Screen Team's Tampa Bay map. Chris Westcott drives from New Port Richey into <a href=\"tampa-screen-repair.html\">Tampa</a>, <a href=\"brandon-screen-repair.html\">Brandon</a>, <a href=\"carrollwood-screen-repair.html\">Carrollwood</a>, and <a href=\"town-n-country-screen-repair.html\">Town 'n' Country</a> on dedicated Hillsborough days — not as an afterthought when a Pinellas route ends early. When homeowners search <strong>screen repair Hillsborough County</strong>, they want the same owner on the ladder they talked to on the phone.",
            "Hillsborough cages skew large: 1990s–2010s subdivisions in Brandon and <a href=\"riverview-screen-repair.html\">Riverview</a>, two-story footprints in Carrollwood and <a href=\"citrus-park-screen-repair.html\">Citrus Park</a>, and in-town Tampa lots where side-yard access and power lines change ladder approach. Chris prices height and access upfront — especially on tall cages where a per-panel quote that ignored the second story would be dishonest.",
            "East-county growth adds newer enclosures in Riverview and <a href=\"valrico-screen-repair.html\">Valrico</a> with shallow gutters under young oaks — the same drainage failure pattern Chris sees in Wesley Chapel across the county line. Historic porch screens and downtown-adjacent lanais in <a href=\"temple-terrace-screen-repair.html\">Temple Terrace</a> and <a href=\"plant-city-screen-repair.html\">Plant City</a> round out the mix with smaller jobs that still meet the visit minimum when bundled thoughtfully.",
            "Cross-bay scheduling means travel is confirmed when you book — no surprise add-on when Chris crosses the Howard Frankland or Veterans Expressway. Batch your Hillsborough stop with a clear city pin: Tampa near Westshore is not the same morning as Brandon east of I-75. Text <a href=\"tel:7273866562\">(727) 386-6562</a> with address, cage photos, and whether you need a full <a href=\"rescreens.html\">pool cage rescreen</a>, partial storm repair, or a <a href=\"pool-enclosures.html\">new enclosure inquiry</a>.",
            "Priority Hillsborough work mirrors Pinellas and Pasco demand: enclosure-wide mesh replacement when oxidation is uniform, <a href=\"gutters-and-screens.html\">super gutters</a> when water sheets off the cage roof into the header spline, and partner-path new builds when permits apply. <a href=\"lutz-screen-repair.html\">Lutz</a> and Citrus Park border Pasco — mention if you also need work on the west side of the county line.",
            "Hillsborough homeowners often discover Screen Team after a bad experience with rotating crews — quotes that changed on arrival, mesh that looked loose within weeks, nobody answering the follow-up call. Chris stays owner-direct: the voice on the phone climbs the cage, and the workmanship guarantee has a name attached.",
        ],
        "Cities we serve in Hillsborough County",
        [
            ('<a href="tampa-screen-repair.html"><strong>Tampa</strong></a>', "in-town access, Westshore cages, urban lanais"),
            ('<a href="brandon-screen-repair.html"><strong>Brandon</strong></a>', "east-county pools, large 1990s enclosures"),
            ('<a href="carrollwood-screen-repair.html"><strong>Carrollwood</strong></a>', "two-story cages, tall ladder quotes"),
            ('<a href="town-n-country-screen-repair.html"><strong>Town \'n\' Country</strong></a>', "west Tampa cages, bay-adjacent wear"),
            ('<a href="riverview-screen-repair.html"><strong>Riverview</strong></a>', "growth subdivisions, new oak gutter clogs"),
            ('<a href="valrico-screen-repair.html"><strong>Valrico</strong></a>', "family pools, pet-damaged door panels"),
            ('<a href="plant-city-screen-repair.html"><strong>Plant City</strong></a>', "historic porches, rural-edge enclosures"),
            ('<a href="lutz-screen-repair.html"><strong>Lutz</strong></a>', "Pasco border, executive cage footprints"),
            ('<a href="citrus-park-screen-repair.html"><strong>Citrus Park</strong></a>', "north Tampa tall cages, Carrollwood adjacency"),
            ('<a href="temple-terrace-screen-repair.html"><strong>Temple Terrace</strong></a>', "Hillsborough River adjacency, mid-century lanais"),
        ],
        "<strong>Cross-bay routing:</strong> Hillsborough jobs are scheduled on dedicated Tampa days — travel confirmed at booking. Border cities (<a href=\"lutz-screen-repair.html\">Lutz</a>, <a href=\"citrus-park-screen-repair.html\">Citrus Park</a>) sometimes pair with <a href=\"pasco-county-screen-repair.html\">Pasco</a> stops.",
        "Priority work: full rescreens, new enclosure inquiries, super gutters",
        [
            "Full <a href=\"rescreens.html\">pool cage rescreens</a> dominate Hillsborough calls once mesh turns chalky cage-wide — common on Brandon and Riverview pools built during the east-county boom. Chris strips failed screen, checks posts and doors, and installs new mesh with spline tension. Tall Carrollwood and Citrus Park cages may span two days when bay count and ladder staging demand it; you hear that range before booking, not after setup.",
            "Need a new pool enclosure on a vacant pad or replacing a storm-collapsed structure? Chris opens the <a href=\"pool-enclosures.html\">new enclosure partner path</a> for permits and engineering while remaining your local contact from NPR. Structural rebuilds are not hidden inside a rescreen line item — Chris says so upfront.",
            "Super gutters fix the Hillsborough pattern of undersized troughs drowning under cage roof area — especially on newer Riverview and Valrico homes where landscaping matured into oak canopy faster than drainage was designed for. Pair <a href=\"gutters-and-screens.html\">gutters and screens</a> when headers stay wet after every afternoon cell.",
            "Partial scope stays available: storm-torn roof horizontals, dog-damaged doors in Brandon family pools, and single-bay patches in Town 'n' Country when surrounding mesh still has life. Chris recommends full rescreen when oxidation is uniform — mixing new and brittle panels fails within a season on Tampa Bay sun.",
        ],
        "Cross-bay humidity, east-county storms, and tall Tampa cages",
        [
            "Afternoon squalls track across Hillsborough from the Gulf and unzip roof horizontals before walls show stress. Chris replaces torn bays with proper tension when aluminum is plumb — see <a href=\"storm-screen-repair.html\">storm screen repair</a>. Uniform chalky mesh means a full rescreen is the honest answer.",
            "Tall cages in Carrollwood, Citrus Park, and north Tampa need height priced upfront. Upper roof panels take harder UV and storm leverage — partial upper-bay work is possible when lower walls are sound; Chris notes if color mismatch will show between new and aged mesh.",
            "Pet-resistant upgrades on abuse doors are common in Valrico and Brandon households. Cross-bay humidity accelerates spline failure on west-facing doors in Town 'n' Country. Chris checks latch alignment and adjacent wall tension — a door that will not seal is often a symptom of slack neighboring panels, not mesh alone.",
        ],
        [
            ("tampa-screen-repair.html", "Tampa"),
            ("brandon-screen-repair.html", "Brandon"),
            ("carrollwood-screen-repair.html", "Carrollwood"),
            ("riverview-screen-repair.html", "Riverview"),
            ("town-n-country-screen-repair.html", "Town 'n' Country"),
            ("pinellas-county-screen-repair.html", "Pinellas hub"),
            ("pasco-county-screen-repair.html", "Pasco hub"),
            ("rescreens.html", "Full rescreens"),
            ("gutters-and-screens.html", "Super gutters"),
            ("pool-enclosures.html", "New enclosures"),
            ("storm-screen-repair.html", "Storm repair"),
            ("service-areas.html", "All areas"),
        ],
        [
            ("Do you serve all of Hillsborough County?", "Yes — Tampa, Brandon, Carrollwood, Riverview, Valrico, Plant City, Lutz, and border communities. Travel is confirmed when you book cross-bay days."),
            ("Is there an extra charge for Hillsborough vs Pasco?", "Cross-bay travel is included in the quoted price upfront — no surprise add-on when Chris drives from NPR."),
            ("How much does a pool cage rescreen cost in Hillsborough?", "Full rescreens often start near $1,995 with most cages landing $2,500–$6,500+ depending on size, height, and access. Tall Carrollwood cages may run higher — Chris ballparks from photos."),
            ("Can you rescreen two-story cages in Hillsborough?", "Yes. Height and ladder setup are priced into the initial range — not discovered mid-job."),
            ("Can you help with a brand-new pool enclosure?", "New enclosure inquiries use the licensed partner path when permits apply. Chris stays your local contact — start on pool enclosures."),
        ],
        [
            ("<strong>Confirm your city pin</strong>", "Tampa westshore vs Brandon east are different cross-bay routes."),
            ("<strong>Photo full height</strong>", "Wide shot showing second story if applicable."),
            ("<strong>Ask about gutters</strong>", "If water sheets off the cage roof, mention super gutters early."),
        ],
        "Hillsborough County screen repair — cross-bay owner-direct service.",
        [
            (G["pano3"], "Pool cage rescreen Hillsborough County Tampa"),
            (G["tall"], "Two-story enclosure Carrollwood Hillsborough"),
            (G["cage2"], "Lanai screen repair Brandon"),
            (G["mesh"], "Mesh replacement Tampa Bay cage"),
        ],
        [
            (G["pano1"], "Wide pool cage — Hillsborough County"),
            (G["work"], "Completed enclosure work — Tampa area"),
        ],
        area_type="AdministrativeArea",
    ),
]
